### ISSUE TITLE
dotnet-test shows duplicate skip and error messages

### ISSUE THREAD

**Issue by natemcmaster** [xunit/visualstudio.xunit#113]
The skip and error messages display twice when using dotnet-test, once by xunit, and again by the VSTest host. It's fine for one or two tests, but when there are lots of errors or skipped messages, the console output can be hard to grok.

Would be nice if the duplication was off by default. But if the vstest abstraction somehow makes that impossible for xunit to implement, is there some kind of RunSetting or logger setting we can use to suppress this?

**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>
</Project>
```
```c#
using System;
using Xunit;

public class UnitTest1
{
    [Fact(Skip = "Skipped this test")]
    public void Test1()
    {
    }
}
```
```
dotnet test
```
**Result**

The skip message is show twice, once by xunit, and again by the VSTest host.

![image](https://user-images.githubusercontent.com/2696087/32581700-dbed2d48-c49f-11e7-9147-dc456d9f59b6.png)

**Comment by bradwilson** [comment]
This is working as designed. One is output from us, one is output from VSTest.

**Comment by kieranbenton** [comment]
@natemcmaster did you ever find another work around for this? 

I find it hard to understand how this was closed without further discussion. Surely duplicating output when you're trying to read failure information from a console isn't the intended behaviour?

**Comment by bradwilson** [comment]
@kieranbenton Because we have no control over what VSTest decides to show vs. not show. It's an external issue.

**Comment by kieranbenton** [comment]
@bradwilson can you shed some light on where the responsibility split is? From the outside it looks like xunit itself just supressing its console output would do the trick here, but from what you've said it sounds like its not as easy as that?

**Comment by bradwilson** [comment]
We don't have console output here; we send messages to VSTest and it chooses which of those messages to show you or not.

The closest thing we could do would be to add a new reporter switch that doesn't report any messages, ever. (We have `quiet` that that only reduces the messages, it doesn't eliminate them.)

**Comment by bradwilson** [comment]
@natemcmaster @kieranbenton A new `silent` reporter: https://github.com/xunit/xunit/commit/dc28c5de21954f65cb0d2fc6e108b3eb4f10419a

* Available in `xunit.runner.console`: `2.6.2-pre.16`
* Available in `xunit.runner.visualstudio`: `2.5.4-pre.11`

For console runner, you can use `-silent` (note that without output to tell you what's happening, you will need to rely on a results file via something like `-xml` or `-html`):

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/6b3f1143-5949-4081-a98f-ca5b025733bd)

For the VSTest adapter, you will select it via RunSettings: https://xunit.net/docs/runsettings#ReporterSwitch (I will update those docs to include the `silent` switch value once this ships RTM):

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/2a6f006e-1d86-4fa1-89c2-38d362dc05f8)
