### ISSUE TITLE
Vstest adapter makes test return The underlying connection was closed: An unexpected error occurred on a send..

### ISSUE THREAD

**Issue by FredrikAlmen** [xunit/visualstudio.xunit#121]
Hi

So started to use xunit after using mstest for some while. I installed the  xunit.runnes.visualstudio Nuget.(And the other nugets needed)
Then when i try to run my tests that tries to send a request with a restsharp RestClient i get the following error 
The underlying connection was closed: An unexpected error occurred on a send..

I tried to run with xunit.console from command line it works perfectly fine, and the tests work with mstest as well. So I am guessing its some problem with the xunit.runner.visualstudio adapter?

I use version 2.4.1 of xunit.runner.visualstudio

Otther setups
4.7.1.net framework
Visual studio professional version 15.9.7
Windows 10

Is this someone else have seen. Anyone have any ideas why it happens?

**Comment by donruperto** [comment]
I have the same problem but no solution yet.

**Comment by bradwilson** [comment]
Please re-open with a repro project. Thanks!
