### ISSUE TITLE
Dotnet test throwing System.IO.FileLoadException

### ISSUE THREAD

**Issue by Frankwayne** [xunit/visualstudio.xunit#122]

**Comment by htimmer** [comment]
Any updates on this issue? I run into the same error. My unit test project is targeting NETFramework, Version=v4.6.2. Locally using the VS Test Explorer my test are all ok, but using the dotnet.exe test command either locally or in Azure DevOps gives the mentioned `Catastrophic failure`

**Comment by bradwilson** [comment]
Sorry for the delay in getting to this issue.

I have upgraded as much as I could in the repro, and I'm now unable to repro the problem, so I assume it's been solved by now. Please open a new issue with a modern repro if you're still experiencing any problems.
