### ISSUE TITLE
Doesn't work with VS 2019 UWP Projects

### ISSUE THREAD

**Issue by jsiemens** [xunit/visualstudio.xunit#124]
I cannot run tests for UWP in VS 2019.

I created a brand new UWP test project, added references to xunit 2.4.1 and xunit.runner.visualstudio 2.4.1, and tried to run the tests.

I get this warning in the tests console, and no tests are run (they *are* discovered):

[4/12/2019 11:01:53 AM Warning] No test matches the given testcase filter `FullyQualifiedName=UnitTestProject2.UnitTest1.TestMethod1` in entrypoint\UnitTestProject2.exe

Works fine in VS 2017. Works fine with VS 2019 and MSTest.

**Comment by bradwilson** [comment]
We have officially deprecated support for UWP, since Microsoft has deprecated it as well.
