### ISSUE TITLE
Xunit won't run Unit Tests for UWP on VS2019

### ISSUE THREAD

**Issue by ScottyLightnin** [xunit/visualstudio.xunit#126]
Since upgrading Visual Studio to 2019, our UWP solution no longer runs the xunit tests.
It can discover them, but when we try to run the tests we get an error similar to:

> No test is available in entrypoint\XunitTestUWP.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Opening the same solution in VS2017, the tests successfully run.

I created a repro project here to demonstrate:
https://github.com/ScottyLightnin/XUnitTestUWP

**Comment by bradwilson** [comment]
Likely dup of #124 and #125 (you opened the latter one).

**Comment by ScottyLightnin** [comment]
Sorry, I came into the office today and couldn't see my original issue. I thought I was going crazy as I was sure I'd submitted it on Friday.
Thank you.

**Comment by bradwilson** [comment]
You're not crazy: I moved them both from [xunit/xunit](https://github.com/xunit/xunit/issues) to here. 😉

**Comment by hooligan495** [comment]
I'm having the exact same problem ... AFter spending a bunch of time today looking through past issues I found this issue.

**Comment by ScottyLightnin** [comment]
Any update on this issue? Our team are keen to move to using VS2019, but this is a blocker for us. There was talk of migrating away from XUnit to enable us to upgrade to VS2019...

**Comment by ScottyLightnin** [comment]
*crickets*...

well, VS2019 v16.1 was released today. I upgraded and gave that a try, but the issue remains.
@bradwilson any insight to whether this is getting looked at, or what the delay is?
It would seem to me that having xunit not work at all on the latest version of Visual Studio, with UWP is a fairly serious flaw..

**Comment by bradwilson** [comment]
Sorry, I don't work on this any more. It's owned by @onovotny.

**Comment by onovotny** [comment]
I haven’t had time to look but the interfaces didn’t change. Have you filed a bug with Visual Studio yet with the report a problem tool?

**Comment by hooligan495** [comment]
It looks like someone has filed an issue with VS.  I went searching.  seems like the VS team couldn't reproduce so I referred that issue back to this one.

**Comment by bradwilson** [comment]
They couldn't repro it, even though the issue includes a pointer to the repro project? :thinking:

**Comment by hooligan495** [comment]
Super bad communication on my part 😜 
The way I read it was this: 
Someone not on this thread also say the issue and reported the problem to MS.  But didn't give them real code to test with.  MS looked into what this person said and said "We need more, we can't make the problem happen" So I pointed the people on the VS issue to this ticket saying "here is a sample that Scotty has posted that you should be able to reproduce with"
I'm hoping they see my link and come to the git repo @ScottyLightnin  has posted and will make progress

**Comment by ScottyLightnin** [comment]
Thanks guys. As a matter of interest I am still experiencing this issue on the latest preview builds of VS2019 (16.2.0 Preview 2.0), in addition to 16.1.3

![image](https://user-images.githubusercontent.com/9923326/59805935-d7dba280-9346-11e9-87dd-a4579c549614.png)

It's frustrating because we love xUnit and we love VS2019, we just want them both to play nicely together for our UWP solutions!

**Comment by mayankbansal018** [comment]
@ScottyLightnin , apologies for delay on this, the issue lies in VS IDE, where we are not sending the xunit adapter path to UWP app, where the test is running.
I'll follow up with the UWP team internally, & will update once a fix is made by them.

/cc @lukewestendorf

**Comment by hooligan495** [comment]
Looks like they have a fix implemented... just need them to make it available

https://developercommunity.visualstudio.com/content/problem/591645/xunit-tests-not-running.html

**Comment by mayankbansal018** [comment]
Yes, I just checked the PR associated with it, & that should fix the issue

**Comment by MairwunNx** [comment]
The other day version 16.2.0 was released, and finally !! Tests work 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉!

**Comment by ScottyLightnin** [comment]
Yep, confirming that my original issues are resolved with 16.2.0
Thanks everyone.

**Comment by scabir** [comment]
I have the same issue with VS 2019 16.3.6

**Comment by qimmer** [comment]
Samme issue here with VS 2019 16.2.4.
Please reopen this case.

**Comment by onovotny** [comment]
Can you please use the Report a problem tool and reproduce it? This is a VS issue, not an xUnit one.

**Comment by mayankbansal018** [comment]
Will try it again on latest VS to confirm.

**Comment by mayankbansal018** [comment]
Just tried on latest VS with repro https://github.com/ScottyLightnin/XUnitTestUWP/tree/master/XUnitTestUWP , & was able to run the test.

If you are still facing the issue, please run test via CLI, & enable diagnostics logs for test platform via: https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-traces-using-command-line & share those file with us

If the tests run in CLI, please open a bug in http://developercommunity.visualstudio.com/ for IDE issue
