### ISSUE TITLE
ServicePointManager.SecurityProtocol not matching framework

### ISSUE THREAD

**Issue by daryllabar** [xunit/visualstudio.xunit#128]
I'm testing a Microsoft Sdk for CRM.  CRM has changed recently to require tls 1.2  Normally this is resolved by upgrading the target build framework to 4.6.2 or greater.  I've done this, but when I check my ServicePointManager.SecurityProtocol value, it's "Ssl3 | Tls" rather than "Tls12" and I'm unable to connect to CRM.   I'm not sure if I'm not truly running 4.6.2 (my properties window for my Test project is setup as such), or if something in xunit is manually setting this.  My simple work around is to just set the SecurityProtocol manually, but I'd prefer not to.  

Any help that you can give would be appreciated.

**Comment by daryllabar** [comment]
I took a look at the csproj: https://github.com/xunit/visualstudio.xunit/blob/master/src/xunit.runner.visualstudio/xunit.runner.visualstudio.csproj

Looks like it is set to target the 4.5.2 framework, so even if my unit test targets a newer framework, it won't be respected since the main app, the runner, is on 4.5.2.  Is this correct?  Am I missing something?

**Comment by onovotny** [comment]
There's ever only one version of the .NET Framework on a machine. The xUnit libraries are compiled for .NET 4.5.2, but if you have a later one installed, it'll be running on that.
