### ISSUE TITLE
Error loading solution with .net core project referencing xunit 2.4.0 in VS 2019

### ISSUE THREAD

**Issue by wimpleshapers** [xunit/visualstudio.xunit#129]
I have a VS 2019 solution that contains one .net core 2.2 class library project which references NuGet packages xunit and xunit.runner.visualstudio 2.4.0.  When the solution is opened for the first time the following message appears:

![image](https://user-images.githubusercontent.com/22672752/58151918-c2cd0000-7c30-11e9-8d15-e60a8c743e88.png)

But I can't find any evidence that shows it matters whether you hit Add or Cancel.  Any suggestions as to what is going on here or how to prevent this message?

**Comment by onovotny** [comment]
This is a Visual Studio issue and this dialog appears related to Team Foundation Version Control. Please open the issue up with them.
