### ISSUE TITLE
TargetFramework netcoreapp3.0 

### ISSUE THREAD

**Issue by vpaulino** [xunit/visualstudio.xunit#144]
Create XUnit project targeting dotnetcoreapp3.0 and the following error appears in the output:

> 
> Test run will use DLL(s) built for framework .NETCoreApp,Version=v1.0 and platform X86. Following DLL(s) do not match framework/platform settings.
> Application.Tests.dll is built for Framework 3.0 and Platform AnyCPU.
> Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
> 
> [6/24/2019 2:44:45 PM Error] Testhost process exited with error: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1' was not found.
>   - The following frameworks were found:
>       1.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       1.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       1.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       1.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.2.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.2.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       3.0.0-preview6-27804-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> You can resolve the problem by installing the specified framework and/or SDK. 

there is no support to target dotnetapp 3.0 previews ? 

Im using this nugets : 

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0-preview-20190606-02" />
		<PackageReference Include="Moq" Version="4.8.2" />
			<PackageReference Include="xunit.analyzers" Version="0.10.0" />
		<PackageReference Include="xunit" Version="2.4.1" />
	 <PackageReference Include="xunit.runner.console" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

```

**Comment by onovotny** [comment]
xUnit works fine with .NET Core 3, what do you get when you do `dotnet --info` from the same directory as the project?

**Comment by vpaulino** [comment]
These are the frameworks that are listed in the test project folder:

![image](https://user-images.githubusercontent.com/859157/60027263-0e8e2180-9695-11e9-9316-23ad446d5c2d.png)

**Comment by onovotny** [comment]
What is the full output and how are you trying to run the tests?

**Comment by vpaulino** [comment]
I have updated the image! I have tried several options... from visual studio with live running without live running, with dotnet test and also from cake script using XUnit2 tool

**Comment by onovotny** [comment]
if you go to the folder of the test project and run `dotnet test`, what is the output? What is the full `csproj` of the test project?

**Comment by vpaulino** [comment]
The content of csproj is this: 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>filename.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
 
  <ItemGroup>
    <ProjectReference  ... to some dotnetstandard2.0 projects />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.2.0-preview-20190606-02" />
  </ItemGroup>

</Project>

**Comment by vpaulino** [comment]
Here is the output of running dotnet test:

![image](https://user-images.githubusercontent.com/859157/60027936-5a8d9600-9696-11e9-853c-22817bc40dd2.png)

**Comment by vpaulino** [comment]
also one more thing... I also have tried sharing nuget packages references using Directory.Build.props file in the folder that haves all my tests projects ... and I thing I found out the problem:
Could it be related to the RuntimeFrameworkVersion ?

```

<Project>

	<PropertyGroup>
		<TargetFrameworks>netcoreapp3.0</TargetFrameworks>
		**<RuntimeFrameworkVersion>2.1</RuntimeFrameworkVersion>**

		<IsPackable>false</IsPackable>

		<DebugType>full</DebugType>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0-preview-20190606-02" />
		<PackageReference Include="Moq" Version="4.8.2" />
			<PackageReference Include="xunit.analyzers" Version="0.10.0" />
		<PackageReference Include="xunit" Version="2.4.1" />
	 <PackageReference Include="xunit.runner.console" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
        <PackageReference Include="FluentAssertions" version="4.19.4" />
		<PackageReference Include="NSubstitute" version="3.1.0" />
		 <PackageReference Include="Newtonsoft.Json" version="9.0.1" />
	</ItemGroup>
	

</Project>
```

**Comment by onovotny** [comment]
Yes, RuntimeFrameworkVersion is overriding the default and .NET Core 3 cannot run on .NET Core 2.1.

**Comment by vpaulino** [comment]
I have commented that attribute and same error happens. What do I need to put there ? the exact version of the dotnet core 3.0 runtime preview version ?

**Comment by onovotny** [comment]
You don't need to specify that attribute at all. Have you cleaned all of your bin/obj directories and tried again to ensure it was rebuilt correctly?

**Comment by vpaulino** [comment]
my bad ! problem fixed ! sorry to disturb you guys!

**Comment by vpaulino** [comment]
> xUnit works fine with .NET Core 3, what do you get when you do `dotnet --info` from the same directory as the project, how are you trying to run xUnit?
> 
> `xunit.runner.console` is no longer supported BTW.

What is the recomended way to run code coverage with xunit then ?

**Comment by onovotny** [comment]
Coverlet is the best way currently as it's cross platform:

https://github.com/tonerdo/coverlet#quick-start

**Comment by vpaulino** [comment]
And that brings me some problems then because currently they have this issue open: https://github.com/tonerdo/coverlet/issues/110
wich means without runner console available I do not have any way to do codecoverage is that it ?

**Comment by onovotny** [comment]
You can use the Microsoft code coverage on VSTest but it only works on Windows.

This PR was just merged, which means it'll be in the nightlies of .NET Core 3 Preview 7 very soon. I don't know exactly how long it takes to fully integrate.

https://github.com/dotnet/toolset/pull/1275

**Comment by vpaulino** [comment]
Can you give any details why xunit.runner.console is no longer supported ?

**Comment by bradwilson** [comment]
It was a compatibility nightmare. We were doing many undocumented things trying to get it to work with the help of the .NET team, and it sort of only just barely works some of the time. The .NET team still uses it (and we kept shipping even after deprecating it, at their request) but they do so knowing that they'll get no support from us if it's broken.
