### ISSUE TITLE
Pretty Display Name for Test Cases stopped working in Visual Studio 2019

### ISSUE THREAD

**Issue by urig-develeap** [xunit/visualstudio.xunit#154]
## Steps to reproduce
1. Open Visual Studio 2019
2. Create a new .Net Framework Class Library project
3. Manage Nuget packages and add `xunit` (v2.4.1) and `more.xunit.runner.visualstudio` (v2.3.1).
4. Create a new `[Fact]` method in a class. Give it a "pretty" name. Ex: `this_test_has_a_pretty_nameX21()`.
5. Add an `app.config` file that enables pretty names like so:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="xunit.methodDisplay" value="method" />
    <add key="xunit.methodDisplayOptions" value="all" />
  </appSettings>
</configuration>
```
6. Open the Test Explorer window.

## Expected Behavior
The test should appear in the window with a pretty name: `this test has a pretty name!`

## Actual Behavior
The test appears in the window with an ugly name: `this_test_has_a_pretty_nameX21` :(
Please see this screenshot:
![image](https://user-images.githubusercontent.com/47077649/60818491-6d2fc100-a1a6-11e9-8a36-1d268606b37b.png)

## Note
If you repeat the exact steps above in Visual Studio 2017, you get the expected behavior.

## Repo with repro
Will be uploaded to github in a few minutes.

**Comment by onovotny** [comment]
Please report this using the VS feedback tool. This is likely an issue with the way they discover tests using source instead of via discovery.
