### ISSUE TITLE
Visual Studio unable to discover test when using TestFramework assembly directive

### ISSUE THREAD

**Issue by dijner** [xunit/visualstudio.xunit#158]
I have extended the XunitTestFramework class and added a assembly directive in my test project. My class get executed and everything works as I would expect. However Visual Studio (visualstudio.xunit I guess) does not discover my tests any longer. If I comment out the assembly directive (about the test framework) Visual Studio finds my test cases and I can debug them, but as soon as i uncomment the assembly directive the tests disappears from visual studio.

I have not overridden the CreateDiscoverer method, the standard XunitTestFrameworkDiscoverer is returned.

*EDIT1:* Added link to video visualizing the issue

Visualization: https://imgur.com/a/RBKIiu5

**Comment by bradwilson** [comment]
Marked as "external" as this behavior comes from VSTest's source-based discovery.
