### ISSUE TITLE
Skipping test case with duplicate ID

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/visualstudio.xunit#161]
It seems likely that some parameters like enums are ignored when generating the uniqueID for the test case:

```
[xUnit.net 00:00:22.20] System.Text.RegularExpressions.Tests: Skipping test case with duplicate ID '0479233059ec774692180dc489ec3da92404bb82' ('System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Repetition_Throws' and 'System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Repetition_Throws')
```

The source indicates that the test is invoked twice with different parameters: https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs#L399

The diagnostics log above tells me that the parameter is not part of the unique ID calculation. Therefore we get a bunch of "Skipping test case with duplicate ID" warnings in corefx when using vstest.

Might be related to `InlineData` only.

cc @onovotny @bradwilson @stephentoub

**Comment by ViktorHofer** [comment]
Is this a dupe of https://github.com/xunit/xunit/issues/1640#issuecomment-364833486?

**Comment by ViktorHofer** [comment]
This seems to be related to our xunitextensions like the `ConditionTheoryAttribute`: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Attributes/ConditionalTheoryAttribute.cs

**Comment by ViktorHofer** [comment]
Sorry for the noise here. @safern I believe you wrote the discoverer, right? The pre-enumerate theories option is not used in our code: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs#L22

Any idea how to make that work?

**Comment by ViktorHofer** [comment]
OK one more post. I believe we are missing this override: https://github.com/aspnet/Extensions/blob/master/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryDiscoverer.cs#L44-L64

**Comment by safern** [comment]
I’ll take a look.

**Comment by ViktorHofer** [comment]
Ok closing as we fixed that on our side.
