### ISSUE TITLE
Parameterized tests appear in Visual Studio's Test Explorer as one when input includes F#-specific types

### ISSUE THREAD

**Issue by bender2k14** [xunit/visualstudio.xunit#162]
I am using xUnit's `MemberData` attribute to write theory-style tests and run them in Visual Studio 2019 (version 16.1.6).  If any types involved are F# specific, then all of the parameterized tests show up in Visual Studio's Test Explorer as a single test.

The example below uses the F#'s `list` type to reproduce this issue.  I am also able to reproduce this issue using a discriminated union.

### Reproduction Steps

Run this test.

```
module TestModule

  open Xunit

  type TestType () =
    static member TestProperty
      with get() : obj[] list =
        [
          [| [0]; "a" |]
          [| [1;2]; "b" |]
        ]
    
    [<Theory>]
    [<MemberData("TestProperty")>]            
    member __.TestMethod (a:int list) (b:string) =
      Assert.Equal(1, a.Length)
```

### Actual Behavior

The two parameter-specific tests of this one parameterized test are displayed in Visual Studio's Test Explorer as a single test.

![Screenshot 2019-07-31 08 52 20](https://user-images.githubusercontent.com/34664007/62219231-91308d80-b373-11e9-8069-545605540c99.png)

### Expected Behavior

I expected the two parameter-specific tests of this one parameterized test to be displayed in Visual Studio's Test Explorer as separate tests.

For a specific example with the expected behavior, run this test...

```
module TestModule

  open Xunit

  type TestType () =
    static member TestProperty
      with get() : obj[] list =
        [
          [| 0; "a" |]
          [| 1; "b" |]
        ]
    
    [<Theory>]
    [<MemberData("TestProperty")>]            
    member __.TestMethod (a:int) (b:string) =
      Assert.Equal(1, a)
```

...which looks like this:

![Screenshot 2019-07-31 08 11 59](https://user-images.githubusercontent.com/34664007/62219411-e53b7200-b373-11e9-94ad-ebf8a8f35de7.png)

**Comment by onovotny** [comment]
Please file a report with Microsoft using the Report a Problem button. The Test Explorer is there window. 

You can also try disabling the Source-based discovery feature in the VS preferences and see if that helps.

**Comment by bender2k14** [comment]
Oh, the issue is the lack of `IXunitSerializable` on those types.  This issue is a duplicate of [xunit/xunit/issues/429](https://github.com/xunit/xunit/issues/429).
