### ISSUE TITLE
Test explorer doesn`t run xUnit tests

### ISSUE THREAD

**Issue by Molnarmala** [xunit/visualstudio.xunit#166]
Test explorer only runs xUnit (Theory with MemberData) tests if I do a Clean Solution and Build Solution first, otherwise it say:
"[2019-08-11 11:43:18 Informational] ========== Run test finished: 0 run (0:00:00.4764217) =========="

Even after I managed to successfully run these tests if I modify the code, I need to clean and build again.

**Comment by bradwilson** [comment]
Closed due to lack of repro project. Please open a new issue with a repro project if this is still occurring.
