### ISSUE TITLE
Short Name Option Ignored for Theories in F#

### ISSUE THREAD

**Issue by isoquark** [xunit/visualstudio.xunit#17]
* Environment: Beta 4 of Xunit 2.0, version 0.99.8 of the xUnit.net runner, F# project
* xunit option to use the short display name is set to TRUE

Unlike facts, theories are displayed with fully-qualified namespace/module names making the content of the Test Explorer difficult to read. 

For example, suppose I define a test function like so

```
namespace A.B

module C =
    [<Theory>]
    [<InlineData(1,3,4)>]
    [<InlineData(1.0, 3.0, 4.0>]
    let testSum x y expect = Assert.Equal(expect, x + y) 
```

Then, the test explorer displays

```
A.B.C.testSum<Int32>(x:1,y:3,expect:4)
A.B.C.testSum<Double>(x:1,y:3,expect:4)
```
I would expect to see something like:

```
testSum<Int32>(x:1,y:3,expect:4)
testSum<Double>(x:1,y:3,expect:4)
```
This appears to be the same issue that was described (and resolved?) by https://xunit.codeplex.com/workitem/9910 If it was fixed, it doesn't appear to be fixed any longer or perhaps this issue is unique to F#.

**Comment by bradwilson** [comment]
This is fixed in RC2.
