### ISSUE TITLE
Issue with member data in linux platform

### ISSUE THREAD

**Issue by prashit** [xunit/visualstudio.xunit#177]
Below tests works fine in windows environment (one fails and rest success) but goes into infinite running when running in ubuntu environment.

None - If all tests are passing, it completes correctly. Issue is only when one or more tests fail and there is a member data function which generates little more (around 10+) test data.

        [Fact]
        public void TestName()
        {
            Assert.Equal(true, false);
        }

        public static IEnumerable<object[]> TestData()
        {
            for (var i = 0; i < 20; i++)
            {
                yield return new object[] { i };
            }
        }

        [Theory]
        [MemberData(nameof(TestData))]
        public void ProcessTest(int i)
        {
        }

**Comment by TheArchitectIO** [comment]
i have the same exact issue when a tests fails on my linux test runner.

I use a docker image for testing and the infinite loop only happens when a test fails.

Docker Image in use is I am using is 
mcr.microsoft.com/dotnet/core/sdk:3.0.100-bionic

**Comment by bradwilson** [comment]
I am unable to reproduce this issue. It may have been fixed since this was opened.

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/6e37d962-7188-4139-8cd4-806a30f465c7)
