### ISSUE TITLE
The active test run was aborted. Reason: Test host process crashed

### ISSUE THREAD

**Issue by agr** [xunit/visualstudio.xunit#184]
Repro:
1. `git clone https://github.com/NuGet/NuGet.Services.Metadata.git`
2. Open the `NuGet.Services.Metadata.sln` solution in VS 2019 (in my case, latest preview);
3. Build and run all tests.

A few seconds after starting the test run, the following is output to the test window:
```
[11/12/2019 2:43:34.421 PM] ---------- Run started ----------
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:02.53]   Starting:    CatalogMetadataTests
[xUnit.net 00:00:08.28]   Finished:    CatalogMetadataTests
[xUnit.net 00:00:09.43]   Starting:    CatalogTests
[xUnit.net 00:00:42.33]   Finished:    CatalogTests
[xUnit.net 00:00:43.39]   Starting:    NgTests
The active test run was aborted. Reason: Test host process crashed
[11/12/2019 2:44:24.863 PM] ========== Run aborted: 0 tests run (0:00:50.4243786) ==========
```
One test in "NgTests" category is not run after it (although high level icons indicate success): `NgTests.SearchIndexFromCatalogCollectorTests.ThrowsIfCommitTimesOut`.
If I run it alone, it fails the same way:
```
[11/12/2019 2:54:06.581 PM] ---------- Run started ----------
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (32-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:00.80]   Starting:    NgTests
The active test run was aborted. Reason: Test host process crashed
[11/12/2019 2:54:10.590 PM] ========== Run aborted: 0 tests run (0:00:03.9936851) ==========
```
Same tests run with console runner (apparently, we use version 2.1.0) work fine.

**Comment by bradwilson** [comment]
The build fails here:

![image](https://user-images.githubusercontent.com/16944/68719593-4f61d680-0561-11ea-872c-23aa9c8f79b3.png)

**Comment by agr** [comment]
Oh, it seems VS has to have "Azure development" workload installed so it can build that project.

**Comment by bradwilson** [comment]
This is a very large project with custom build steps. Any chance you can provide a simple repro?

**Comment by agr** [comment]
I figured it out. It's an issue on our side.
[This](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/tests/NgTests/SearchIndexFromCatalogCollectorTests.cs#L178) test line eventually ends up in calling [`Environment.Exit`](https://github.com/NuGet/NuGet.Services.Metadata/blob/f3784b55a5ff39e9917c94160790b08b64438d77/src/Ng/SearchIndexFromCatalogCollector.cs#L144), which "crashes" the test runner.
This also happens with console runner, I just checked our logs, it just happens quiet enough so no one noticed:

```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: NgTests
  Discovered:  NgTests
  Starting:    NgTests
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: NuGet.IndexingTests
  Discovered:  NuGet.IndexingTests
  Starting:    NuGet.IndexingTests
  Finished:    NuGet.IndexingTests
```
(notice no "Finished" line for `NgTests`).

**Comment by agr** [comment]
My concern now is that a test that fails to finish is not indicated in any way on a top level:
![image](https://user-images.githubusercontent.com/102933/68722750-542b8800-056b-11ea-9c7c-5ab38e07e57f.png)

Should it be brought up to VS?

**Comment by bradwilson** [comment]
This is expected behavior. AFAIK, there's nothing we can do to intercept or prevent Environment.Exit.

**Comment by agr** [comment]
That's fair. What about test explorer? Is this a runner-related behavior or VS?

**Comment by bradwilson** [comment]
I would expect they should be able to notice that the process crashed and somehow make note of it.

**Comment by agr** [comment]
Reported to VS.

**Comment by ilatypov** [comment]
Just making the cause found by @agr clear to myself...

https://github.com/NuGet/NuGet.Services.Metadata/blob/master@%7B2019-11-12%7D/tests/NgTests/SearchIndexFromCatalogCollectorTests.cs#L178
