### ISSUE TITLE
Passed test checkmark not showing up correctly in Jenkins log file

### ISSUE THREAD

**Issue by rkeithhill** [xunit/visualstudio.xunit#196]
This is what I see in the log file:

![image](https://user-images.githubusercontent.com/5177512/72817962-e6b16d00-3c27-11ea-8663-6df1d562bc51.png)

Is there a xunit test runner command-line option to have it use `Passed` instead of the checkmark?

**Comment by bradwilson** [comment]
That output is not from xUnit.net. It might be VSTest, or if you're using some third party extensions to xUnit.net, it might also be that.

**Comment by rkeithhill** [comment]
I don't see this issue anymore.
