### ISSUE TITLE
xUnit runner ignores Traits and the .runsettings when running through vstest.console.exe

### ISSUE THREAD

**Issue by rajithaw** [xunit/visualstudio.xunit#20]
I'm using the following command for running my xUnit tests in command line,

vstest.console.exe MyTests.dll /Settings:C:\Tests\Xunit.RunSettings /InIsolation /UseVsixExtensions:false /TestAdapterPath:C:\Tests\xUnit\visualstudio.xunit-master\xunit.runner.visualstudio.testadapter\bin\Debug /TestCaseFilter:"Category=MyCategory"

It looks like the test adapter is not picking up the /Settings and the /TestCaseFilter passed into the vstest.console.exe. The settings provided by the RunSettings file and the filtering by Traits are completely ignored. I'm using build 2745 of the test adapter.

**Comment by bradwilson** [comment]
Fixed by https://github.com/xunit/visualstudio.xunit/commit/6de34af0df51e139d754746adeb1fb3656fe972c
