### ISSUE TITLE
Update reference to Microsoft.NET.Test.Sdk 

### ISSUE THREAD

**Issue by leotsarev** [xunit/visualstudio.xunit#200]
Now `xunit.runner.visualstudio` references old versions of SDK, so consumers could hit i.e. bug like this https://github.com/microsoft/vstest/issues/841 which was cause of silent skipping of unit tests on my Teamcity setup :-) 
What are cons of updating Microsoft.NET.Test.Sdk to latest 15.x at least?

**Comment by temelj** [comment]
I've added a test project to work out why Microsft.NET.Test.Sdk (16.5.0) does not work when you're targeting .NET Core 2.1/2.2

https://github.com/temelj/xunit-mstest-demo

**Comment by bender2k14** [comment]
Yes, I agree.  Increasing the version requirement on `Microsoft.NET.Test.Sdk` will fix bugs for users of your NuGet package.

For example, [here is a](https://github.com/dotnet/fsharp/issues/9653#issuecomment-656293313) bug that exists in version `<= 15.7.0` of `Microsoft.NET.Test.Sdk` but not in version `>= 15.8.0`.  I would have prefered to have avoided this bug by `xunit.runner.visualstudio` requiring a version of `Microsoft.NET.Test.Sdk` no less than `15.8.0`.

**Comment by leotsarev** [comment]
@bradwilson is this correct place to post issues, or it should be moved to main repo?

**Comment by bradwilson** [comment]
This is the right place. /cc @clairernovotny

**Comment by clairernovotny** [comment]
The Test SDK revs far more often than we do -- it tends to match VS. We're never going to keep up and projects should take a direct dependency on the latest version to ensure they get all platform fixes.

**Comment by leotsarev** [comment]
Ok, I'll probably should close issue than
