### ISSUE TITLE
Test case with duplicate ID incorrectly reported

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/visualstudio.xunit#204]
```
  [xUnit.net 00:00:00.89] System.Web.HttpUtility.Tests: Skipping test case with duplicate ID '67e146e9ac56298413839658e54b471a437d5f22' ('System.Web.Tests.HttpUtilityTest.UrlDecode_ByteArray(decoded: "http://exam
ple.net/?a", encoded: "http://example.net/\xd800a")' and 'System.Web.Tests.HttpUtilityTest.UrlDecode_ByteArray(decoded: "http://example.net/?a", encoded: "http://example.net/\xdc00a")')
```

Here you see that `\xd800a` and `\xdc800a` were recognized as the same input even though their  representation is different.

cc @clairernovotny

**Comment by bradwilson** [comment]
This appears to be fixed now, testing with `xunit` 2.5.0-pre.21 and `xunit.runner.visualstudio` 2.5.0-pre.14.

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/83332e34-19be-437e-9e54-fc5f411a7fd4)
