### ISSUE TITLE
Using right-paren ) as InlineData for Theory causes test runner to act strange

### ISSUE THREAD

**Issue by jeoffman** [xunit/visualstudio.xunit#208]
Sample code in .net core or Framework
```
[Theory]
[InlineData(')')]
[InlineData('(')]
public void IsXUnitTestRunnerBrokenTest(char character)
{
    Assert.True(character == character);
}
```
When you "Run All", Visual Studio _Test Explorer_ shows white icons with exclamation marks. If you right click the Unit Test by name and "Run" then it executes and passes both InlineData cases.

**Comment by greendimka** [comment]
I also have experienced this problem.
Here is my sample:

```
[Theory]
[InlineData("", "")]
[InlineData("\"\"\"", ")")]
public void DemoTest(
    string s1,
    string s2)
{
    Assert.True(1 == 1);
}

```

It not only shows white-with-exclamation icons, it actually adds another test to the list of tests within runner. If you try to run this "extra" test together with any other test then none of them are run.
N.B. Everything is OK, if I run "dotnet test"

**Comment by jeoffman** [comment]
@bradwilson  I dug into this a bit and it appears that Visual Studio (2019) is throwing an exception due to an unmatched parenthesis when xunit.runner.visualstudio is calling to IRunContext.GetTestCaseFilter. Something about combinations of tests that include the ) in the test's DisplayName are causing Visual Studio to pass a "TestCaseFilter" parameter on the command-line, and that filter **does** contain a mismatched right-paren. eg (from logs):
"TestCaseFilter": "FullyQualifiedName=Blah.RunSettingsTests.DemoTest|FullyQualifiedName=Blah.RunSettingsTests.DemoTest\"**)**|FullyQualifiedName=Blah.RunSettingsTests.ThisTestWorks",
You can see a spurious ) in the second grouping (between the OR | lines) with FullyQualifiedName=....)|
But the thing is, I am running _all_ tests when that log was generated so the TestCaseFilter should be null (I think?). There must be something about the tests (names?) that is causing VS to pass the bogus "TestCaseFilter" - not sure if this is something wrong with VS, how XUnit generates theory DisplayNames, or a bad combination of both.

Note this behavior explains why right-clicking the individual tests and running them works - EXCEPT when you run that bogus "extra test" (mentioned by @greendimka ) or any combination/group that contains the bogus extra test.

**Comment by bradwilson** [comment]
I am unable to repro this now with VS 2022 and pre-release builds of `xunit` and `xunit.runner.visualstudio` 2.5.0. I suspect the problem has been fixed since this issue was opened.
