### ISSUE TITLE
Directory.GetFiles(UNC Path) does not work

### ISSUE THREAD

**Issue by emi662002** [xunit/visualstudio.xunit#213]
using this code when executing a xunit test
`var baseDir ="\\\\?\\UNC\\storage\\c$\\folder";
 System.IO.Directory.GetFiles(baseDir));`

throws exception "illegal characters in path"

the same code running on MStest works just fine. I guess the problem is that you are using .net 4.5.2 and the "UNC feature" allowing \\?\UNC\ as path prefix works only since .net 4.6.2

**Comment by bradwilson** [comment]
Current minimum version is now 4.6.2, so this should be fixed.
