### ISSUE TITLE
2.4.2 raises minimum version to netcoreapp2.1

### ISSUE THREAD

**Issue by bgrainger** [xunit/visualstudio.xunit#217]
[xunit.runner.visualstudio 2.4.1](https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.1) supported `netcoreapp1.0`.

[xunit.runner.visualstudio 2.4.2](https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.2) raises this to `netcoreapp2.1`.

This was an unexpected change in a SemVer PATCH release (that was expected to contain "backwards compatible bug fixes"), and broke a unit test project I had (that's still supporting some older and EOL TargetFrameworks). I don't disagree with moving ahead and only supporting newer frameworks, but think that it warrants a bigger version bump.

It appears to have been introduced several years ago (but the NuGet package hasn't been updated for a long time): https://github.com/xunit/visualstudio.xunit/commit/7d34623b87c488eb4c7bd11eb46057cdc568e531.

**Comment by bgrainger** [comment]
There was also no mention of this change in the release notes: https://github.com/xunit/visualstudio.xunit/releases/tag/v2.4.2

**Comment by clairernovotny** [comment]
.NET Core 2.1 is the earliest supported runtime by Microsoft.

**Comment by 304NotModified** [comment]
This was an unpleasant surprise. Did not broke tests, but coverage was 0%. Don't get this why this is a patch version change. This should be minor at least!
