### ISSUE TITLE
Update supported frameworks on the Xunit website

### ISSUE THREAD

**Issue by chtoucas** [xunit/visualstudio.xunit#220]
I believe that the list of supported frameworks is now outdated.
https://xunit.net/docs/nuget-packages

**Comment by bradwilson** [comment]
How so?

**Comment by chtoucas** [comment]
Maybe I'm misunderstanding something but, for instance, the Xunit website says that xunit.runner.visualstudio supports .NET Core 1.0+, and the NuGet package v2.4.2 (on nuget.org) says that it supports .NET Core 2.1+.

**Comment by bradwilson** [comment]
Thanks, I've updated the page now to be current with intended support in 2.5.0 (that is, removing mentions of UWP, and pushing minimum versions for `xunit.runner.visualstudio` to `net462` and `net6.0`).
