### ISSUE TITLE
xunit.runner.visualstudio.uwp.targets references to wrong xunit.runner.reporters.netstandardXX.dll

### ISSUE THREAD

**Issue by Mr1Penguin** [xunit/visualstudio.xunit#221]
It references to xunit.runner.reporters.netstandard11.dll while there is a *15.dll in build directory.
It leads to "Payload file does not exist" during test application loading.

**Comment by scottkuhl** [comment]
I ran into this issue in a UWP test project.  The Microsoft.NET.Test.Sdk was set to version 16.0.1 and I tried upgrading both it and the xunit.runner.visualstudio package at the same time. The Microsoft.NET.Test.Sdk failed but the xunit.runner.visualstudio succeeded and then this issue started.  I don't think this is an issue with the xunit runner.  When I upgraded the Test SDK to 16.8 everything worked.

FYI: The reason the Test SDK failed was a problem in project file.  You need to add this manually first to get it to upgrade.

    <PackageReference Include="Microsoft.NET.Test.Sdk">
      <Version>16.0.1</Version>
    </PackageReference>

Or just set to the latest version.

**Comment by lucas-zimerman** [comment]
wow it's still happening.

**Comment by bradwilson** [comment]
Closing, as UWP has been removed from future releases of the adapter.
