### ISSUE TITLE
execute  'dotnet test'  can not find xunit test

### ISSUE THREAD

**Issue by zhoujiazhi222** [xunit/visualstudio.xunit#223]
Test run for /Users/gg/test/Temp/Bin/Debug/Assembly-CSharp.dll(.NETFramework,Version=v4.7.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
No test is available in /Users/gg/test/Temp/Bin/Debug/Assembly-CSharp.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.

**Comment by zhoujiazhi222** [comment]
@bradwilson 
Thank you，But I am not using visualstudio，I am using Rider
[demo.zip](https://github.com/xunit/visualstudio.xunit/files/4802040/demo.zip)

**Comment by zhoujiazhi222** [comment]
@bartelink 
My repo have xunit.runner.visualstudio，but it is still can not work

**Comment by clairernovotny** [comment]
does this reproduce with `dotnet test` on the CLI? What OS are you trying to run it on?

**Comment by zhoujiazhi222** [comment]
@clairernovotny 
Macos 10.15.4

**Comment by zhoujiazhi222** [comment]
And it is my dotnet version
![Uploading Screen Shot 2020-06-19 at 10.14.06 AM.png…]()

**Comment by clairernovotny** [comment]
What does your test target? I don't see a repro but it looks like .NETFramework,Version=v4.7.1. 

.NET Framework tests are only supported on Windows.

**Comment by zhoujiazhi222** [comment]
It is my demo project
[demo.zip](https://github.com/xunit/visualstudio.xunit/files/4802218/demo.zip)

**Comment by zhoujiazhi222** [comment]
@clairernovotny  
How should I use Cli run xunit test in Macos or Linux？

**Comment by clairernovotny** [comment]
It's not supported to run .NET Framework tests on Mac/Linux as .NET Framework does not run there. It may work with mono but that's completely unsupported. .NET Framework must be on Windows .NET Core is cross platform and works on Mac and Linux.

**Comment by zhoujiazhi222** [comment]
@clairernovotny 
I am using .NET Core ，not .NET Framework
<img width="972" alt="Screen Shot 2020-06-19 at 11 23 53 AM" src="https://user-images.githubusercontent.com/20750357/85093652-6b2c0a00-b21f-11ea-8b09-734ec3764abe.png">

**Comment by zhoujiazhi222** [comment]
Please help me get my `demo.zip` running xUnit on MacOS

**Comment by bartelink** [comment]
The message says:
> and platform & framework version settings are appropriate
thus the answer is to follow Claire's advice: change the `TargetFramework`
(Note Rider does tricks that make things seem to work like e.g. running the tests under `mono`)

**Comment by zhoujiazhi222** [comment]
@bartelink 
I try it but failed, Could you please help me solve it using my `demo.zip`

**Comment by bartelink** [comment]
Once again: You'll get quicker and better help on stackoverflow.com (However: there, as here, it always helps to set the context at the start of the conversation rather than revealing that you're doing Mono stuff one day into the conversation)

I had a brief look - that stuff seems to be Mono-focused - `dotnet test` is for .NET Core, not for Mono. So you need to pick a path for your code and your tests in terms of `TargetFramework` - that will then imply the appropriate way to run things, e.g.:
- `net471`, using mono instructions for running tests
- `netcoreapp`*, using `dotnet test` for running tests

**Comment by zhoujiazhi222** [comment]
@bradwilson 
thx ， i will try it
