### ISSUE TITLE
Executing multiple test cases which are mapped to a single automated test

### ISSUE THREAD

**Issue by Prateeksha-tv** [xunit/visualstudio.xunit#225]
Hi,

I am using specflow for writing test cases and xunit as test runner. I have associated multiple test cases in azure devops test plan to a single test case. When the test case execute, expectation is that all the linked test cases should be updated with the result, but only one test case is updated and remaining are marked as In progress.

We have raised this query with microsoft team as well. Below is the reply

> Both XUnit and NUnit does not allow running one test multiple times in the same session. This is therefore not supported. It is only supported in mstest.

Can we have this feature in xunit as well?

**Comment by clairernovotny** [comment]
This issue belongs in xunit/xunit.

**Comment by bradwilson** [comment]
I'm not 100% sure I agree with the VSTest team's analysis.

If we were asked to run a test twice with two separate run requests, we would run it twice. This is functionally no different from you running it once, and then after receiving the result, running it again. We definitely support this.

There may be further complicating issues about _how_ they want to ask us to run something twice that makes it more difficult on their end to do so. But from my perspective, this is a feature we (and every test framework, really) already support. So I'm closing this as an external issue.
