### ISSUE TITLE
No source available for [Fact] in base class in another assembly

### ISSUE THREAD

**Issue by addabis** [xunit/visualstudio.xunit#233]
We've recently migrated to xUnit from MSTest and ran into problems with test discovery in Visual Studio 16.7 (and other IDEs using the VS runner). 

When [Fact] is declared in an abstract base class, which is then derived in a specific class containing tests, it is always discovered. However, the source information on the test cases shown in VS is not correct when the base class is in a different assembly than the derived class. 

See the attached solution. [XUnitBaseFactVisibilityTest.zip](https://github.com/xunit/visualstudio.xunit/files/5057662/XUnitBaseFactVisibilityTest.zip)

There are 5 tests in 2 assemblies and all are discovered:
* BaseLibrary
    * ReferencedSharedTests.TestWithNameInBothAssemblies shown in LocalTests class, source shown in LocalSharedTests.cs. **Incorrect**, source should be in ReferencedSharedTests.cs.
    * ReferencedSharedTests.TestNameOnlyInBaseAssembly shown in LocalTests class, source shown as not available. **Incorrect**, Source should be in ReferencedSharedTests.cs.
* TestLibrary
    * LocalSharedTests.TestWithNameInBothAssemblies shown in LocalTests class, source shown in LocalSharedTests.cs. **Correct.**
    * LocalTests.TestInDerivedClass shown in LocalTests class, source shown in LocalSharedTests.cs. **Correct.**
    * ReferencedTests.TestInDerivedClass shown in ReferencedTests class, source shown in ReferencedTests.cs. **Correct.**

Neither of the tests in BaseLibrary is correctly shown and the second failure can be quite misleading and Rider will not show source code for both TestWithNameInBothAssemblies tests
.

I was unable to locate the source of this behavior myself. Is there any way to make this work correctly?

**Comment by bradwilson** [comment]
Unfortunately, I don't think there's anything we can do here, as the source information is provided to us by [DiaSession](https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.ObjectModel/Navigation/DiaSession.cs) from VSTest. Any bugs related to this should be brought up with that team.
