### ISSUE TITLE
DisableParallelization setting in RunSettings.RunConfiguration node isn't honored when passed in as a CLI argument

### ISSUE THREAD

**Issue by ViktorHofer** [xunit/visualstudio.xunit#241]
The following doesn't invoke test collections in parallel:

a.runsettings:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <DisableParallelization>true</DisableParallelization>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="console">
        <Configuration>
          <Verbosity>Detailed</Verbosity>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
</RunSettings>
```

```
dotnet test a.dll --settings a.runsettings
```

Whereas the following does invoke test collections in parallel (but it shouldn't):

``` 
dotnet test b.dll -settings -- RunSettings.RunConfiguration.DisableParallelization=true
```

**Comment by ViktorHofer** [comment]
@nohwnd do you know if the `SettingsXml` string does contain CLI passed in options? xunit.runner.visualstudio reads from that here: https://github.com/xunit/visualstudio.xunit/blob/a0aa0042a435f02aae14ee18622de287ddce11fd/src/xunit.runner.visualstudio/VsTestRunner.cs#L88.

**Comment by nohwnd** [comment]
The RunSettings node is implied, if you specify it in your inline settings it will put in `RunSettings > RunSettings > RunConfiguration > DisableParallelization` instead of `RunSettings > RunConfiguration > DisableParallelization`.

```
dotnet test b.dll -- RunConfiguration.DisableParallelization=true
```

(in your oringinal command there is also -settings, but that's probably just a typo)

**Comment by ViktorHofer** [comment]
Yes that did it. Sorry for the noise, that's just me not knowing how to use our own tools lol.

**Comment by nohwnd** [comment]
No worries, I had similar problem few days ago as well 😁
