### ISSUE TITLE
Document how to build, test and debug xunit.runner.visualstudio.testadapter.dll

### ISSUE THREAD

**Issue by tapika** [xunit/visualstudio.xunit#252]
I have tried by myself to build xunit v2 - and everything works fine with exception to xunit.runner.visualstudio.testadapter.dll.

At the moment I have tried to build nuget packages manually, using batch like this:

    @echo off
    if %VisualStudioVersion%. == . call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat" >nul
    if NOT "%version%" == "" (
        git restore src\common\GlobalAssemblyInfo.cs
        call powershell -file build.ps1 _setVersion Release %version% %version%
    )

    set MyGetHost=myownnuget_host
    set MyGetApiKey=nuown_apikey

    if "%no_build%" == "" (
        call powershell -file build.ps1 Packages Release %version% %version%
        if errorlevel 1 exit /b 1
    )

    if NOT "%do_publish%" == "" if NOT "%do_publish%" == "0" (
        echo Publishing nuget package...
        call powershell -file build.ps1 _pushmyget
        if errorlevel 1 exit /b 1
    )

But like you probably guess - it's missing nuget package signing completely, that is performed in 
`build.ps1`, `_SignPackages`, and it involves configuration parameters like
`appveyor.yml / MyGetApiKey / SignClientSecret / SignClientUser`

and configuration file like `tools\SignClient\appsettings.json`.

Maybe because of missing signing maybe because of something else - Visual studio does not load nor use `xunit.runner.visualstudio.testadapter.dll` dll completely, even thus it has the same folder structure as earlier release version.
(inside `_common` folder in nuget package).

Would it be possible to document what is needed to configure build environment for xunit test adapter debugging in visual studio, also potentially how to troubleshoot loading problems if any.

Also if xunit v2 vs xunit v3 differs quite heavily - I would prefer to get xunit v2 documentation at least by mail, if not by official documentation.

**Comment by tapika** [comment]
Referred documentation / links which provide more information:

https://github.com/dotnet/SignService#client-configuration
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration
https://github.com/xunit/xunit/issues/457

**Comment by tapika** [comment]
Don't know exactly the reason behind whole story, but apparently if you're compiling your own custom test adapter, you MUST reference it in order for visual studio to detect your project as test project.

For older xunit version it's sufficient to have these lines in test project:

```
  <PropertyGroup>
    <XUnitVersion>99.99.99-dev</XUnitVersion>
    <!--<XUnitVersion>2.4.1</XUnitVersion>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="xunit" Version="$(XUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XUnitVersion)" GeneratePathProperty="true" />
    <PackageReference Include="xunit.runner.console" Version="$(XUnitVersion)" />
  </ItemGroup>
```

However - if you switch from `2.4.1` to `99.99.99-dev` version, you need extra line:

```
  <ItemGroup>
    <Reference Include="xunit.runner.visualstudio.testadapter">
      <HintPath>$(Pkgxunit_runner_visualstudio)/build/_common/xunit.runner.visualstudio.testadapter.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
```

In order for visual studio to recognize your project as a test project.

According to this link:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.8#testadapterextension

All test projects must include their .NET test adapter NuGet reference in their csproj.

But this is not true for xunit 2.4.1. Why ?! That's odd anyway.

**Comment by bradwilson** [comment]
The command-line build process has been overhauled to be in common with the same one used by the core project.

The README.md and BUILDING.md have been updated with build & debug instructions.
