### ISSUE TITLE
xunit.runner.visualstudio 2.4.3 - Unexpected error detected. Test run aborted. 0 total tests 

### ISSUE THREAD

**Issue by iluzek** [xunit/visualstudio.xunit#259]
With latest version xunit.runner.visualstudio 2.4.3.

Created sample project for .net 5 and corresponding .net core (5.0) class library with tests.
Had to change
<TargetFramework>net5.0</TargetFramework> to <TargetFramework>net5.0-windows</TargetFramework> to make it build but it seemed to work after that.

But Visual Studio and Xunit report issues as follow:
Unexpected error detected. Check the Tests Output pane for details.
Test run aborted. 0 total tests - 0 Passed, 0 Failed, 0 Skipped.

I downgraded 
xunit.runner.visualstudio 2.4.1 and without doing anything else it **worked fine**.

Downgrading to 2.4.2 also does **NOT work**.

**Comment by nfplee** [comment]
When I try a build after upgrading to 2.4.3. I get the error:

"Program does not contain a static 'Main' method suitable for an entry point"

I'm not sure if this is related but my solution is to also downgrade to 2.4.1.

**Comment by m4m4m4** [comment]
I noticed this too in our .Net 3.1 pipelines after having upgraded, 2.4.1 does not have this issue

**Comment by thinkershare** [comment]
Visual Studio 2019 Enterprise, 2.4.3 not work too, but I switch to 2.4.1, it work well.

**Comment by bradwilson** [comment]
Closing this as 2.4.5 is the current version, and I haven't heard any other feedback about this being a problem now.
