### ISSUE TITLE
Unmapped warning dialog during restore in VS 2019 when bound to TFS

### ISSUE THREAD

**Issue by agilenut** [xunit/visualstudio.xunit#263]
When creating a test project with a package reference to xunit.runner.visualstudio, we get the following warning dialog complaining that we are attempting to add unmapped items to a source controlled solution:
![ScreenCapture at Mon Mar 29 15:41:40 EDT 2021](https://user-images.githubusercontent.com/705864/113016828-d7438300-914c-11eb-95bc-450a086fc171.png)

Steps to reproduce:
* Create a new solution and xUnit project
* Add solution to source control (TFS)
* Close solution
* Delete bin and obj directories in order to force a restore upon open
* Open solution
* Observe warning during restore

I've narrowed it down to this package. When I comment out the package reference, the warning does not appear. 

Is there a way to prevent this? 

I need to have the package installed so that developers can run tests in Visual Studio. But they also complain about these warnings. I do not want to ask developers to choose to always ignore these warnings because they do occasionally help us find issues where other developers have accidentally added items as content in custom nuget packages.

**Comment by bradwilson** [comment]
This seems like a better question for the Visual Studio (or TFS source control provider) teams. It's not clear from your post (or the dialog box, for that matter) what files it things are outside of source control. Installing a NuGet package should never cause such an error message.
