### ISSUE TITLE
Skip attribute on [InlineData] is not respected in Visual Studio

### ISSUE THREAD

**Issue by martincostello** [xunit/visualstudio.xunit#266]
If the `Skip` property of an `[InlineData]` attribute (or derived types of `DataAttribute`) is populated with a message that it should be skipped, either statically in code or at runtime, Visual Studio does not respect that value and runs the test when the Visual Studio Test Explorer is used.

A repo containing a solution that demonstrates this issue can be found here: https://github.com/martincostello/broken-inlinedata-skip-repro

This appears to be a regression since xunit 2.3.1.

Running `dotnet test` using the CLI is not affected:

```ps
PS C:\Coding\broken-inlinedata-skip-repro> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Coding\broken-inlinedata-skip-repro\bin\Debug\netcoreapp2.1\broken-inlinedata-skip-repro.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.98]     BrokenInlineDataSkip.Tests.Can_Add_Integers(x: 2, y: 2, expected: 4) [SKIP]
Skipped  BrokenInlineDataSkip.Tests.Can_Add_Integers(x: 2, y: 2, expected: 4)

Total tests: 2. Passed: 1. Failed: 0. Skipped: 1.
Test Run Successful.
Test execution time: 2.2485 Seconds
```

## xunit 2.3.1 Behaviour

<img src="https://user-images.githubusercontent.com/1439341/43956632-da4111be-9c9c-11e8-8a48-22ec44d0196c.PNG">

## xunit 2.4.0 Behaviour

<img src="https://user-images.githubusercontent.com/1439341/43956637-e20c4aa8-9c9c-11e8-92ba-1da7d07a4ae0.PNG">

**Comment by bradwilson** [comment]
Fixed in 2.4.2-pre.14 (currently on MyGet). The serialization of this class has changed in v3 with the move to traditional .NET Serialization, so the issue is not present in v3.

**Comment by bradwilson** [comment]
> When will this be available as on nuget.org as a non-prerelease?

Soon, but no fixed date yet.

**Comment by Issung** [comment]
I am still encountering this issue with `2.4.5` has it worked its way into that release or is it still pending release?

Test
![image](https://user-images.githubusercontent.com/22212465/205524490-b2e567d0-9fb3-4b6f-bb99-1cc0d151ea9c.png)
Test Results
![image](https://user-images.githubusercontent.com/22212465/205524514-b5a1ca8a-c88e-4104-98a2-87badec2c465.png)
DLL Version proof
![image](https://user-images.githubusercontent.com/22212465/205524569-084068ac-19b8-4efc-b24c-9ac6e7b86b33.png)

**Comment by bradwilson** [comment]
@Issung wrote:

> I am still encountering this issue with 2.4.5 has it worked its way into that release or is it still pending release?

This should be fixed w/ xUnit.net 2.4.2. Make sure you've upgraded the core framework package(s).

**Comment by jzabroski** [comment]
Works great for me.  You need to use both Xunit and Xunit.runner to be successful, though.

**Comment by Issung** [comment]
Ah that is where I fell short, must also update the base xunit package, I have done that now and it works perfect, thanks for your effort on this bug!

![image](https://user-images.githubusercontent.com/22212465/205531343-4fd1935d-5fd0-4879-8f3f-ca3a96e55407.png)
