### ISSUE TITLE
Inconsistent behavior with empty InlineData

### ISSUE THREAD

**Issue by cwood77** [xunit/visualstudio.xunit#279]
Consider the following test method:

```C#
      [Theory]
      [InlineData("this works")]
      [InlineData("this", "also", "works")]
      [InlineData] // test explorer: The test method expected 1 parameter value, but 0 parameter values were provided.
                   // dotnet test: pass
      public void Test1(params string[] arguments)
      {
      }
```

It's the third `InlineData` case that's interesting.  In this case, no arguments are provided as inline data.  When run from `dotnet test`, all three cases pass, but when run from Test Explorer in Visual Studio, the test fails with `The test method expected 1 parameter value, but 0 parameter values were provided.`

I could perhaps be convinced that the error behavior is actually the correct one.  But either way it seems wrong that the test behaves differently depending on how it's run.

**Comment by rsrobinett** [comment]
I'm experiencing the same issue.  When using "Unit Test Session" or `dotnet test` it works, but fails in the "Test Explorer".  In my case I have default parameters.    It works if there is at least one parameter, but not when there is none. 

        [Theory]
        [InlineData("this works")]
        [InlineData("this", "also", "works")]
        [InlineData] // test explorer: The test method expected 3 parameter values, but 0 parameter values were provided.
        // dotnet test: pass
        public void Test1(string argument1 = "default1", string argument2 = "default2", string argument3 = "default3")
        {
        }

**Comment by bradwilson** [comment]
This appears to be a dup of #371 where I've already done some investigation, so closing this one.
