### ISSUE TITLE
Tests with timeout attribute do not finish in TestExplorer

### ISSUE THREAD

**Issue by bradwilson** [xunit/visualstudio.xunit#28]
See s/o question: http://stackoverflow.com/questions/26184327/unit-test-keep-running-in-test-explorer-even-after-timeout-excedded

**Comment by robi-y** [comment]
Somehow the problem returned to a fresh VS2013, here is the test runner output, is it because it is still looking for the old xunit.dll assembly?
------ Discover test started ------
[xUnit.net 00:00:00.0000014] Discovery started
[xUnit.net 00:00:00.0005145] Skipping: ClassLibrary3.dll (<strong>no reference to xUnit.net</strong>)
[xUnit.net 00:00:00.0007105] Discovery complete
========== Discover test finished: 0 found (0:00:00.1064244) ==========

**Comment by robi-y** [comment]
@bradwilson take a look at source file https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L204
It tries to specifically load 'xunit.dll' shouldn't it be now 'xunit.core.dll' ?

**Comment by robi-y** [comment]
happy to report that RC-1 fixed this issue for me (VS2013 Update 4), thanks

**Comment by Crono1981** [comment]
Experiencing this issue with v2.4.1 in Visual Studio 2019.

```cs
[Fact(Timeout = 5000)]
public void Timeout()
{
    while (true) ;
}
```

My xunit.runner.json file (in same folder as the test project) is set as such:

```json
{
  "parallelizeTestCollections": false
}
```

**Comment by bradwilson** [comment]
This issue is closed. Please open a new issue with a repro project. Thanks!

**Comment by antoinebj** [comment]
> 
> 
> Experiencing this issue with v2.4.1 in Visual Studio 2019.
> 
> ```cs
> [Fact(Timeout = 5000)]
> public void Timeout()
> {
>     while (true) ;
> }
> ```

For anyone encountering this: It appears that xUnit timeout is only supported for async Task methods that yield back to the synchronization context (i.e. use await) at least once before any blocking occurs.

Short explanation for this behavior is that xUnit blocks on [`TestInvoker.CallTestMethod`](https://github.com/xunit/xunit/blob/2.4.1/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L257) and can never return a task representing the method execution. It would have got such a task if it reached either [`await task`](https://github.com/xunit/xunit/blob/2.4.1/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L264) or [`await asyncSyncContext.WaitForCompletionAsync();`](https://github.com/xunit/xunit/blob/2.4.1/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs#L268).

The following works:
```cs
[Fact(Timeout = 5000)]
public async Task Timeout()
{
    await Task.Yield();

    while (true) ;
}
```

**Comment by onovotny** [comment]
Does it happen with the command line as well?

**Comment by antoinebj** [comment]
@onovotny Indeed it does. I believe it would be correct to assume that it does not have anything to do with Visual Studio.

**Comment by onovotny** [comment]
Please file a new issue in https://github.com/xunit/xunit for this. Thanks.
