### ISSUE TITLE
`GetRunnerReporter` crashes on `Microsoft.JSInterop.WebAssembly`

### ISSUE THREAD

**Issue by JeroenBos** [xunit/visualstudio.xunit#282]
## Bug description

My xUnit tests fail because the visual studio runner crashes. Specifically, I've traced it to [this line](https://github.com/xunit/visualstudio.xunit/blob/0a20790c1dd788e3fac13788506f3aba1b28afd1/src/xunit.runner.visualstudio/VsTestRunner.cs#L715) which throws a `ReflectionTypeLoadException`.

Normally I would conclude assembly is corrupt, however this case may be special, given that it occurs for the dll `Microsoft.JSInterop.WebAssembly.dll` (I've reproduced for versions from .NET 5.0.8 and .NET 6.0 preview 6), and I trust Microsoft to not have published a corrupt assembly. Even outside of the context of xUnit, this particular assembly simply is not reflection-loadable, e.g. the following crashes too:
```csharp
using System.Reflection;
static void Main(string[] args)
{
    foreach(Type t in Assembly.LoadFrom("path/to/net5.0.8_or_net6.0/Microsoft.JSInterop.WebAssembly.dll").DefinedTypes)
    {
    }
}
```

The proposed solution for this crash is that visualstudio runner should 
a) skip this particular assembly in checking for runner reports, or
b) catch this exception, disregarding any runner reporters in the assembly, if any

### Context 

I started getting this error when upgrading my blazor WebAssembly project from .NET Core 3.x to .NET 5, really only the 2 PackageReferences `Microsoft.AspNetCore.Components.WebAssembly(.DevServer)`. After that the visual studio runner crashes (because the assembly only has this behavior from .NET 5)

### Versions
I have VS 16.10.4 and use
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
<PackageReference Include="xunit" Version="2.4.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
```

### Exception details

```
Unable to load one or more of the requested types.

System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
```
```
LoaderException[0]: Generic method or method in generic class is internal call, PInvoke, or is defined in a COM Import class.
LoaderException[1]: Could not load type 'WebAssembly.JSInterop.JSCallInfo' from assembly 'Microsoft.JSInterop.WebAssembly, Version=5.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' because it contains an object field at offset 4 that is incorrectly aligned or overlapped by a non-object field.
```

Stacktrace:
<details>
<pre>
<code>
System.Private.CoreLib.dll!System.Reflection.RuntimeAssembly.DefinedTypes.get()
xunit.runner.visualstudio.dotnetcore.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.GetAvailableRunnerReporters(System.Collections.Generic.IEnumerable<string> sources) Line 715
xunit.runner.visualstudio.dotnetcore.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.GetRunnerReporter.AnonymousMethod__0() Line 663
System.Private.CoreLib.dll!System.Lazy<System.Collections.Generic.IReadOnlyList<Xunit.IRunnerReporter>>.ViaFactory(System.Threading.LazyThreadSafetyMode mode)
System.Private.CoreLib.dll!System.Lazy<System.Collections.Generic.IReadOnlyList<Xunit.IRunnerReporter>>.ExecutionAndPublication(System.LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Private.CoreLib.dll!System.Lazy<System.Collections.Generic.IReadOnlyList<Xunit.IRunnerReporter>>.CreateValue()
System.Private.CoreLib.dll!System.Lazy<System.__Canon>.Value.get()
xunit.runner.visualstudio.dotnetcore.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.GetRunnerReporter(LoggerHelper logger, Xunit.Runner.VisualStudio.RunSettings runSettings, System.Collections.Generic.IEnumerable<string> assemblyFileNames) Line 675	
xunit.runner.visualstudio.dotnetcore.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.RunTests(Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, LoggerHelper logger, Xunit.Runner.VisualStudio.TestPlatformContext testPlatformContext, Xunit.Runner.VisualStudio.RunSettings runSettings, System.Func<System.Collections.Generic.List<Xunit.Runner.VisualStudio.AssemblyRunInfo>> getRunInfos) Line 442	
xunit.runner.visualstudio.dotnetcore.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor.RunTests(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle) Line 210	
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension<Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor, Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestExecutorCapabilities> executor, System.Tuple<System.Uri, string> executorUri, Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.RunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(System.Collections.Generic.IEnumerable<System.Tuple<System.Uri, string>> executorUriExtensionMap, long totalTests)
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestsInternal()
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTests()
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.ExecutionManager.StartTestRun(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, string package, string runSettings, Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ClientProtocol.TestExecutionContext testExecutionContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ITestCaseEventsHandler testCaseEventsHandler, Microsoft.VisualStudio.TestPlatform.ObjectModel.Client.ITestRunEventsHandler runEventsHandler)
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.OnMessageReceived.AnonymousMethod__4()
Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler..ctor.AnonymousMethod__20_2(System.Action action)
Microsoft.TestPlatform.CoreUtilities.dll!Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.Action>.SafeProcessJob(System.Action job)
Microsoft.TestPlatform.CoreUtilities.dll!Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.Action>.BackgroundJobProcessor()
Microsoft.TestPlatform.CoreUtilities.dll!Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.__Canon>..ctor.AnonymousMethod__12_0()
System.Private.CoreLib.dll!System.Threading.Tasks.Task.InnerInvoke()
System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__284_0(object obj)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread threadPoolThread)
System.Private.CoreLib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler..cctor.AnonymousMethod__10_0(object s)
System.Private.CoreLib.dll!System.Threading.Thread.StartCallback()
</code>
</pre>

</details>

**Comment by bradwilson** [comment]
That line of code is wrapped in a try/catch, so it's not clear to me how you're seeing an exception. The net result should be that the assembly in question is ignored the purposes of finding reporters.

Can you provide a repro project?

**Comment by JeroenBos** [comment]
Closing, as I can't reproduce it anymore. It's been a long time.
