### ISSUE TITLE
Existence of xunit.runner.json causes error Azure Pipelines (dotnet.exe failed with exit code 1)

### ISSUE THREAD

**Issue by emreaydinceren** [xunit/visualstudio.xunit#283]
Although all tests pass and publish test results succeed error:
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1

The content of the config
```
{
    "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
    "methodDisplay": "method",
    "methodDisplayOptions": "all"
}
```

Works fine, local calling this via dotnet.exe test .. or running from Visual Studio Test Explorer

**Comment by bradwilson** [comment]
Can you provide more information? On its face, this appears to be an Azure Pipeline problem.

**Comment by bradwilson** [comment]
Closing for lack of repro project. Please open a new issue with a repro if this is still occurring. Thanks!
