### ISSUE TITLE
.NET 6 Support?

### ISSUE THREAD

**Issue by RehanSaeed** [xunit/visualstudio.xunit#285]
I'm upgrading my projects to .NET 6. When running a build on GitHub Actions where I install the .NET 6 RC1 SDK and then run `dotnet test`, I get the following errors:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.1.21451.13 at [/home/runner/.dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.1.21451.13 at [/home/runner/.dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
```

My class library and xUnit test projects multi-target several target frameworks:

```xml
<TargetFrameworks>net6.0;net5.0;netcoreapp3.1;net472</TargetFrameworks>
...
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
```

Does the latest version of xUnit 2 support .NET 6? My understanding was that GitHub Actions already had several SDK versions installed but it looks like maybe installing .NET 6 got rid of previous versions (.NET 5 did not do this). Apologies if I raised this issue in the wrong repo (should it be vstest?), hard to know where it went wrong.

**Comment by pensono** [comment]
If you're using `setup-dotnet`, all frameworks must be installed.

https://github.com/actions/setup-dotnet/issues/136
