### ISSUE TITLE
Is there any supported way of stopping on failure?

### ISSUE THREAD

**Issue by jeff-simeon** [xunit/visualstudio.xunit#286]
This used to be supported via the CLI, but dotnet-xunit seems to have been deprecated since 2.4. Is there any supported way of using dotnet test and stopping on first failure? Or if not is there any hack or workaround? Waiting for all of our acceptance tests to run in CI before we know about a failure has reached a breaking point for us and we need to evaluate whether to move off xunit. 

Thank you

**Comment by bradwilson** [comment]
Dup of #189
