### ISSUE TITLE
the stack trace line is error

### ISSUE THREAD

**Issue by AiSY-Yang** [xunit/visualstudio.xunit#288]
when i run a test in visual studio,the stack trace line is error
like this
![image](https://user-images.githubusercontent.com/20870087/140245642-cbe4f9f7-c46c-4aef-8bc6-24151e392595.png)
dotnet 5.0 is right ,line number is 126
![image](https://user-images.githubusercontent.com/20870087/140245613-da38b875-1ec8-4b6c-aa59-03a8569c0ed9.png)
dotnet 3.1 is wrong, line number of  stack tarce is 127 ,actual is 126
![image](https://user-images.githubusercontent.com/20870087/140246543-ecfa6c20-6a95-4fad-b3a1-44f8e2969167.png)
and if i comment some line, the stack trace line is end of comment

the code is https://github.com/AiSY-Yang/ExtensionMethods/tree/c257b01fbea6608b2e1ea3d64297132f1846c941
forgive me for not copy core code in a demo, i do this and discover problem is no longer arose

**Comment by bradwilson** [comment]
We don't control how stack traces are generated; we just display them. This looks like it was a bug in .NET Core 3.1 that has since been fixed in .NET 5. Closing this as an external issue.
