### ISSUE TITLE
InlineData attribute with a string with certain symbols breaks VS Test Explorer with badly grouped entries

### ISSUE THREAD

**Issue by djturner** [xunit/visualstudio.xunit#289]
Creating a Theory with an InlineData attribute with a string with certain symbols breaks VS Test Explorer.

Seems recreatable with a string containing one escaped quotation mark character, followed later by a right parenthesis. Does not occur when there are two escaped quotation mark characters before the parenthesis, or where the parenthesis comes before the quotation mark.

The result is false entries in VS Test explorer, alongside correctly grouped ones. If you try to run any group of tests containing the false entries, then the tests appear to run but then do not return a result - only previous stale results are shown. This makes VS Test Explorer difficult to use for common tasks (i.e. "Run All Tests").

Code to reproduce:
```cs
using Xunit;

namespace MyUnitTests
{
    public class Class1
    {
        [Theory(DisplayName = "Test")]
        [InlineData("1: This is grouped properly")]
        [InlineData("2: \"This is also grouped properly\"()")]
        [InlineData("3: \"This creates a false entry in a new group()")]
        [InlineData("4: ()But this doesn't create a false group\"")]
        [InlineData("5: \")")]
        [InlineData("6: )\"")]
        public void Test(string mydata)
        {
            Assert.DoesNotContain(")", mydata);
        }
    }
}

```
Resulting entries in test explorer in a cleaned project are incorrectly grouped:
![image](https://user-images.githubusercontent.com/1162627/144411898-f86e87ac-7aa3-4a89-a9c3-6f84007714c6.png)

Resulting entries in test explorer after building the project shows all test cases in the `Test` group, but the false entries in `Test"` remain:
![image](https://user-images.githubusercontent.com/1162627/144412034-a4973633-a6d0-4648-a95c-8e88a2c59f00.png)

Test run results below. Note, I'm cleaning and rebuilding the project between each run to clear existing results.

Trying to run the `Test` group returns results as expected:
![image](https://user-images.githubusercontent.com/1162627/144412421-79c73a64-2acf-4b01-bdc2-d47ce08c5512.png)

Trying to run the false `Test")` group looks like it tries to run, but then doesn't return results:
![false-group](https://user-images.githubusercontent.com/1162627/144413178-82cbe35e-b2aa-4afa-b1e8-609e1dffe4b7.gif)

Trying to run all tests, or all test in the namespace or class, again it looks like it tries to run something, but doesn't return results - even for valid entries. The same behaviour is seen for "Run All Tests".
![namespace-with-false-group](https://user-images.githubusercontent.com/1162627/144413203-04ed05e4-d69b-48be-96df-6d731f1880bb.gif)

**Comment by djturner** [comment]
Versions of software this issue has been seen with:
- xunit 2.4.1
- xunit.runner.visualstudio 2.4.1, and 2.4.3
- Visual Studio 2019 (16.11.7)

Colleague also reports seeing the same issue in VS 2022, but I don't know what build.

**Comment by JakubJanowski** [comment]
Same issue in
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0

**Comment by nkehrein** [comment]
Can confirm this with
* xunit 2.4.1
* xunit.runner.visualstudio 2.4.3
* Visual Studio Professional 2022 (64bit) 17.1.5

**Comment by EmanterolaDN** [comment]
Same issue here with char parameter ')'
![image](https://user-images.githubusercontent.com/73877504/222430424-d1e0d9cb-353c-48a0-8058-46f49e9f2f6a.png)

    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
    VS community 2022 x64 17.3.6

**Comment by bradwilson** [comment]
This bug belongs to VSTest, not us. Please open an issue with them.
