### ISSUE TITLE
Race Condition With IClassFixture

### ISSUE THREAD

**Issue by kvbutler25** [xunit/visualstudio.xunit#290]
See below code I had to manually synchronize. Unless I am using it wrong I would expect behavior of Ctor() then Dispose() before the next test class Ctor(), Dispose, ....

What I was actually seeing is `Ctor()` from `TestClass2` called before `Dispose()` from `TestClass1`

XUnit version is 2.40.

Let me know if I'm off base, thanks!

P.S. This workaround is doing fine for those who need

```C#
public class DbContextFixture : IDisposable
  {

    private static readonly SemaphoreSlim Mutex = new SemaphoreSlim(1);

    public DbContext DbContext { get { return TestUtils.CreateDbContext(); } }

    public DbContextFixture()
    {
      Mutex.Wait();
      var ctx = TestUtils.CreateDbContext();
      ctx.Database.EnsureCreated();
    }

    public void Dispose()
    {
      try
      {
        DbContext.Database.EnsureDeleted();
      }
      finally
      {
        Mutex.Release();
      }
    }
  }
```

**Comment by bradwilson** [comment]
This is working as designed. Multiple instances of a fixture will be created if they are for different test collections (by default, each test class is a test collection with just itself in it).

If you want to have a single DbContextFixture that's shared amongst many test classes, then it should be marked as a collection fixture (not a class fixture), and all those test classes need to be in the single test collection that has that as a fixture.

For more information, see the docs: https://xunit.net/docs/shared-context#collection-fixture
