### ISSUE TITLE
MemberData tests are sometimes being skipped in VS Test Runner 

### ISSUE THREAD

**Issue by kakins** [xunit/visualstudio.xunit#302]
The frequency appears to be random.

I choose to run all tests under a folder:
![image](https://user-images.githubusercontent.com/14915247/155194085-044e7ddb-fe90-4a8e-bb3c-6b8bd982d6e4.png)

The tests will run and complete, with the exception of some.  The only thing they have in common is that they use `MemberData.`
![image](https://user-images.githubusercontent.com/14915247/155194190-4148eea8-1930-4c88-878b-603a8937df58.png)

If I perform the same steps a second time, all the tests complete, even the `MemberData` tests.

**Comment by bradwilson** [comment]
Can you provide a full repro project and exact repro steps? Thanks!

**Comment by kakins** [comment]
This has been a while and I haven't run into it lately.
