### ISSUE TITLE
Why do the latest GitHub releases have an extra ".1" appended?

### ISSUE THREAD

**Issue by adamralph** [xunit/visualstudio.xunit#309]
![image](https://user-images.githubusercontent.com/677704/167083978-b73f31a0-6fed-4ab1-acd0-c97214e8c487.png)

![image](https://user-images.githubusercontent.com/677704/167084071-bdace67a-81cf-48e8-b422-64fbeb4cef23.png)

It's the same for 2.4.4.1/2.4.4 although that version seems to have been unlisted from the NuGet gallery.

**Comment by bradwilson** [comment]
Thanks, I've fixed this.
