### ISSUE TITLE
IMO 2.4.5 should have been a major version bump

### ISSUE THREAD

**Issue by SimonCropp** [xunit/visualstudio.xunit#311]
since it drops support for 

- netcore2.1
- netcore2.2
- netcore3.0
- net461

![image](https://user-images.githubusercontent.com/122666/167275866-ece410f1-bc60-4622-8f9e-bd73698c021e.png)

![image](https://user-images.githubusercontent.com/122666/167275869-cb97bf39-bf58-4b42-bc6d-b4324614486d.png)

**Comment by clairernovotny** [comment]
xUnit does not follow SemVer and there shouldn't be any impact to any supported frameworks.

**Comment by SimonCropp** [comment]
xunit not following semver should not imply that this package should also not follow semver.

I was just surprised when my builds broke for a patch release.

But looks like this was intentional. so i will close this one

**Comment by SimonCropp** [comment]
@clairernovotny seem weird we just had a new release of xunit [that still targets net45 and netcore2.1](https://www.nuget.org/packages/xunit.extensibility.core/#supportedframeworks-body-tab) when the current release of this packages means it is not possible to run those tests

**Comment by bradwilson** [comment]
People on older frameworks need to stay on 2.4.3 of the VSTest adapter.
