### ISSUE TITLE
Runner not finding / running tests in my project

### ISSUE THREAD

**Issue by christav** [xunit/visualstudio.xunit#34]
So I created a new project following the directions in http://xunit.github.io/docs/getting-started.html. When I try to run via the command line or the Resharper runner, everything works fine. However, when I use the VS runner, the test explorer show this:

![test explorer](https://cloud.githubusercontent.com/assets/1987321/5466702/956b9cb4-8565-11e4-8bd6-33acdedd83d5.png)

Click run all, and I get this in the VS output window:
```
------ Run test started ------
No test is available in D:\Dev\RunnerReproSln\RunnerReproSln\bin\Debug\RunnerReproSln.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
========== Run test finished: 0 run (0:00:00.557163) ==========
```

Running individual tests give me:

```
------ Run test started ------
========== Run test finished: 0 run (0:00:00.3372456) ==========
```

I've restarted VS, rebuilt the project, still no luck.

Repro project is at https://github.com/christav/RunnerRepro2.

**Comment by giggio** [comment]
Ok, I just ran `devenv /ResetSettings` and VS 2015 was able to find the tests again. I am not sure if it was a problem with VS or xunit, so I am just reporting back here so you are aware.

**Comment by wholroyd** [comment]
In the several minutes it took me to find this bug for the same issue being reported, my Test Explorer lit up correctly on it's own. It might be some sort of performance issue in the runner where it takes longer than expected to perform whatever discovery is going on.

VS 2013 Ultimate, ReSharper 9, NuGet only, VSIX never.

**Comment by fubar-coder** [comment]
I had the same problem where those Xunit tests were not found. The reason was, that in 
```
c:\Users\%username%\AppData\Local\Temp\VisualStudioTestExplorerExtensions\xunit.runner.visualstudio.0.99.9-build1021\build\
```

the _common folder (with the required assemblies) where missing.

After copying the _common folder from the xunit.runner.visualstudio.0.99.9-build1021 package and a VS restart, the unit tests were found again.

**Comment by mayerwin** [comment]
Same problem here (VS 2013 Update 4). Resharper could discover Xunit tests but not the Test Explorer VS window. 
I tried uninstalling Xunit packages but when I tried to reinstall afterwards, it failed due to paths being too long (a nuget error). So I moved my solution folder closer to the root C:\, reinstalled Xunit packages and then moved my solution back to its original folder... Not sure if it was what helped but now it works. Hopefully it can help others with the same issue.

**Comment by robi-y** [comment]
This one solved it for me with rc1-build1030, thanks

**Comment by giggio** [comment]
Ok, there is a weird pattern going on here. I am really confused. Maybe @bradwilson can tell if he has seen this before.

First problem is: I am not sure if we still need the `xunit.runner.visualstudio` package from nuget. I am using version `2.0.0-rc1-build1030` on [CodeCracker](https://github.com/code-cracker/code-cracker) for C#, and it will not show tests in VS without it. But I don't need a reference to it on the VB Solution. I have not idea why. So the first question is: is this package still needed when using Xunit `2.0.0-rc1-build2826`? BTW, I am using VS 2015 CTP 5.

Second problem is: I have another project, also using Xunit `2.0.0-rc1-build2826` and runner `2.0.0-rc1-build1030`, that will not show tests on test explorer in VS unless I load some other project that has Xunit, like CodeCracker, on VS, before. So, if I open CodeCracker, then open that project, it works and shows my tests, but if I open it directly in VS, it will not show the tests, and even weirder, if I then close the first project and open CodeCracker, VS will not show CodeCracker's tests.

I am really confused with all this. I need some guidance on how to orchestrate all of this dependencies and how to correctly setup the project.

**Comment by bradwilson** [comment]
@giggio:

> I am not sure if we still need the xunit.runner.visualstudio package from nuget. I am using version 2.0.0-rc1-build1030 on CodeCracker for C#, and it will not show tests in VS without it. But I don't need a reference to it on the VB Solution. I have not idea why.

It's an oddity of the Visual Studio runner architecture, but you shouldn't count on this to be true. What's happening is this: so long as one project references the runner, then the runner gets used to discover tests from all DLLs/EXEs, not just the ones that reference the NuGet package. The reason you shouldn't count on this is because we use props and targets files to ensure extra DLLs get copied around for device projects, so while you may accidentally get this to work with extra desktop projects, it won't work with device tests (Win8/WPA81).

> I have another project, also using Xunit 2.0.0-rc1-build2826 and runner 2.0.0-rc1-build1030, that will not show tests on test explorer in VS unless I load some other project that has Xunit, like CodeCracker, on VS, before.

This, I have not seen. Are these projects public? I can try and repro for you.

**Comment by ManeetB** [comment]
Was facing the same issue.
I included the nuget packages for xUnit and xUnit.Runner.

I was able to solve the problem after installing the pre-release package.
This one solved it for me with rc1-build1030, I removed the 1.92 and installed the latert Pre release.
Restarted Visual Studio and It solved the Problem for me.

**Comment by jasper22** [comment]
[fubar-coder answer](https://github.com/xunit/visualstudio.xunit/issues/34#issuecomment-70407054) solved 'test not found' for me. The `c:\Users\%username%\AppData\Local\Temp\VisualStudioTestExplorerExtensions\xunit.runner.visualstudio.0.99.9-build1021\` was empty :( not even `\build` folder was there

**Comment by bradwilson** [comment]
Yep, we've documented that here:

http://xunit.github.io/docs/running-tests-in-vs.html

:(

![Warning](https://cloud.githubusercontent.com/assets/16944/6215989/73ef04a6-b5ba-11e4-95a4-40240abe01fd.png)

**Comment by pvlakshm** [comment]
Thank you for filing a bug in https://connect.microsoft.com/VisualStudio/. I am unable to repro this. If you have a consistent repro for this issue, please let me know (you can either email me at pratapL _at_ microsoft _dot_ com or reach me on twitter at @pvlakshm - we will request you to collect and send across some logs so we can get to the bottom of this.

Thank you once again.
pratap

**Comment by feO2x** [comment]
I faced a similar problem several times when I updated some of my projects from rc1 to rc2 or rc3 - just deleting the *%TEMP%\VisualStudioTestExplorerExtensions* folder wasn't enough to circumvent this problem. I also had to delete the NuGet packages folder where both rc1 and rc2 / rc3 assemblies resided next to each other. Then I started VS and the runner discovered all tests properly.

When I didn't perform these steps, I got the following exception on the first test run after I started VS (subsequent test runs exited immediately without producing any output):

```
------ Load Playlist started ------
========== Load Playlist finished (0:00:00,0060057) ==========
------ Discover test started ------
NUnit 1.2.0.0 discovering tests is started
NUnit 1.2.0.0 discovering test is finished
[xUnit.net 00:00:00.0873763] Exception discovering tests from List.Tests.dll: System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
   at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, IMessageLogger logger, Func`3 visitorFactory, Action`3 visitComplete, Stopwatch stopwatch)
========== Discover test finished: 0 found (0:00:02,99552) ==========
```

I could reproduce this in VS 2013 Update 4 and VS 2015 CTP 6.

**Comment by rumcajz** [comment]
I faced this with VS 2013 Community Update 4 and XUnit 2.0.0. Other projects in the solution were using XUnit 1.9.2 and their tests were discoreved correctly. When I discovered that, the solution was simple: don't use the most recent version of XUnit (2.0.0) and install 1.9.2 for my new project. To do that I had to choose:

Tools > NuGet Package Manager > Package Manager Console

and issue the command:

Install-Package xunit -Version 1.9.2

Don't forget to choose the right project from the dropdown of the Package manager's console.

That solved it for me. If you don't need 2.0.0's features then it might work fine for you too.

**Comment by alexandervantrijffel** [comment]
Thumbs up rumcajz, that worked for me too.

**Comment by ValenteMesmo** [comment]
Thank you, rumcajz!

**Comment by rickszyr** [comment]
I had the same issue. Cleaning, and running tests (before rebuilding) did the trick for me.

**Comment by webgio** [comment]
Visual studio runner with xunit 1.9.2 works fine, with xunit version >= 2 it just doesn't discover tests, it keeps searching. Any idea why? Tried deleting temp folder already. Would love to use Theory tests...

**Comment by webgio** [comment]
Got it... the problem was that I was running visual studio in a VM and code directory was accessed as network resource. Opening the vs solution as mounted volume fixed everything.
