### ISSUE TITLE
VS Runner fails with overloaded tests

### ISSUE THREAD

**Issue by christav** [xunit/visualstudio.xunit#35]
Found this in our codebase today:

```c#
    [Fact]
    public void SomeTest()
    {
        SomeTest("a");
    }

    private static void SomeTest(string s)
    {
        Assert.Equal(1, s.Length);
    }
```

When running from the Resharper or MSBuild runners, this executes fine. However, when using the VS runner, it crashes with an exception something like "Multiple matching items in collection" (sorry I don't have the exact error, I'm not sitting in front of the machine right now).

If the overloading is removed (change the name of the static method or the test) and vs runner is fine again.

(Creating a minimal repro project for this is blocked right now due to #34.)

**Comment by shytikov** [comment]
Really annoying issue... :cry: :cry: :cry: 

In my case it gives following error message:

> The active Test Run was aborted because the execution process exited unexpectedly. To investigate further, enable local crash dumps either at the machine level or for process vstest.executionengine.x86.exe. Go to more details: http://go.microsoft.com/fwlink/?linkid=232477

So far I cannot see any dumps anywhere...

**Comment by bradwilson** [comment]
Given the information that we have when attempting to discover test methods (just the method name), it's unlikely that we're going to be able to fix this. :(
