### ISSUE TITLE
VSTestResult does not report startTime

### ISSUE THREAD

**Issue by nohwnd** [xunit/visualstudio.xunit#359]
Trx includes StartTime and EndTime, and VSTest sets those values to the current timestamp for "backward compatibility". Xunit does not report start time or end time, just duration. 

Would you be open to start tracking this information? I can make a PR. 

https://github.com/xunit/visualstudio.xunit/blob/b0b4704a7c4e1bd901cd50f40e7fd4ea36f0deb2/src/xunit.runner.visualstudio/Sinks/VsExecutionSink.cs#L274

https://github.com/microsoft/vstest/blob/b2e2126f1aa7e5753cafe9515563c99ade6a59ce/src/Microsoft.TestPlatform.ObjectModel/TestResult.cs#L34

**Comment by bradwilson** [comment]
Yes, this can be approximated today for v1 & v2 tests with the arrival of [the start message](https://github.com/xunit/abstractions.xunit/blob/main/src/xunit.abstractions/Messages/ITestStarting.cs). We would just need to stash that information away so it could be retrieved when creating the VSTest `TestResult` after the test has finished.

For v3, we can add this explicitly (we were already planning to do this with [assembly starting](https://github.com/xunit/xunit/blob/2b1f75b320b54edc364785d5d7634deff71784f8/src/xunit.v3.common/v3/Messages/_TestAssemblyStarting.cs#L41), but it can be easily added for all start messages).

**Comment by bradwilson** [comment]
This was implemented in 3ad2641b and released with `3.0.0-pre.20`.
