### ISSUE TITLE
Cannot filter through FullyQualifiedName or DisplayName while discovering tests in test assembly

### ISSUE THREAD

**Issue by ZCao-96** [xunit/visualstudio.xunit#370]
## Background 
Currently, we are developing a feature to get test cases count from a specific test assembly in vstest.console and we want do it with test case filter to make the number more accurate. We happily found that, thanks to @nohwnd's commit [9c651a8](https://github.com/xunit/visualstudio.xunit/commit/9c651a80667bfa8bab016ee3e705e4dfb50778af), we can filter test cases during test discovery.

However, we find out that we cannot filter test assemlies based on xunit through **FullyQualifiedName** or **DisplayName** during **test discovery**. In the mean time, we also find out that we can filter test assemlies based on xunit through **FullyQualifiedName** or **DisplayName** while running the test assembly. 

## Proposed Feature
**To filter test cases through FullyQualifiedName or DisplayName during test discovery**, we navigate to this source code repo and we think that the variable _isDiscovery_ in the file [_TestCaseFilter.cs_](https://github.com/xunit/visualstudio.xunit/blob/86c0e57f3d8458b8b0f5e436f732dd9546d563dd/src/xunit.runner.visualstudio/Utility/TestCaseFilter.cs#L67) is blocking this goal. I am wondering if we could remove this _isDiscovery_ variable since it is its only reference. 

### Now
Every filter during test discovery should only base on Traits.
### Future 
Every filter during test discovery can base on one of these ways: Traits, FullyQualifiedName or DisplayName.
### Action needed
Remove the _isDiscovery_ variable in the file [_TestCaseFilter.cs_](https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/TestCaseFilter.cs).

Maybe @nohwnd would know more context regarding this feature. 

Could anyone help me with this? Thanks!

**Comment by ZCao-96** [comment]
Hey @nohwnd , thank you for your response. I have made some changes in the code but I was blocked when I tried to push the code as below. Is it due to some settings on pull request in this repo? Any ideas?
![image](https://github.com/xunit/visualstudio.xunit/assets/123312912/c1b606fe-49c4-48f6-ad52-4ae028b94bc8)

**Comment by bradwilson** [comment]
@ZCao-96 You'll need to make a fork of this repo into your personal account, push the changes there, and initiate the PR from that fork back to this repo. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by bradwilson** [comment]
Merged in #380

**Comment by ZCao-96** [comment]
Much appreciated for @bradwilson 's quick response! Thank you so much! This change will definitely unblock the feature we are working on. One last small question, when is this change going to be rolled out and available in Production/WorldWide?

**Comment by bradwilson** [comment]
@ZCao-96 I'll put out another prerelease build to NuGet next week. Not sure on a final release date yet.

**Comment by ZCao-96** [comment]
@bradwilson Thanks! That would be enough for me.

**Comment by bradwilson** [comment]
@ZCao-96 https://www.nuget.org/packages/xunit.runner.visualstudio/2.5.1-pre.10

**Comment by ZCao-96** [comment]
@bradwilson Great! Thanks! Looking forward to the official version~
