### ISSUE TITLE
Suggest allows variable arguments to be empty

### ISSUE THREAD

**Issue by xp44mm** [xunit/visualstudio.xunit#371]
I use F# code to demonstrate the problem:

```fsharp
    [<Theory>]
    [<InlineData()>] // **note**
    [<InlineData(1)>]
    [<InlineData(1,2)>]
    member _.``variable arguments`` ([<System.ParamArray>]sq:int[]) =
        for i in sq do
            output.WriteLine($"{i}")
```

expected:

```fsharp
    [<InlineData()>]  => sq = [||]
```

but:

```fsharp
System.InvalidOperationException : The test method expected 1 parameter value, but 0 parameter values were provided.
```

**Comment by xp44mm** [comment]
@bradwilson Your job is irreplaceable by AI!

**Comment by bradwilson** [comment]
I'm still not 100% sure why we get where we're getting, but I was able to put a little escape hatch into the system to say "if we end up here, just pretend we got valid data and move on". I'm not 100% pleased with this, but until/unless I can actually figure out why the values from the VSTest adapter come back incorrect, I'm basically stuck with this semi-hack.
