### ISSUE TITLE
Segregate xunit.runner.visualstudio.dotnetcore.testadapter.dll

### ISSUE THREAD

**Issue by ByteMe666** [xunit/visualstudio.xunit#377]
Hi,

I am using Azure DevOps, and [it is documented that](https://xunit.net/docs/getting-test-results-in-azure-devops) xunit.runner.visualstudio.dotnetcore.testadapter.dll should be excluded from being considered a test assembly.

Unfortunately when using Release Pipelines in Azure DevOps and choosing to associate the xUnit tests with Test Cases from a Test Plan [as per this documentation](https://learn.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops), no menu is available and \*test\*.dll is used by default.

I was hoping to remedy the issue by moving all my actual test assemblies to their own folder and telling Azure DevOps to look for them there. I could do that manually with a BASH of BATCH script in the build pipeline I guess, but I was hoping to do it the "clean" way by configuring properly my .csproj file in the first place.

However it is really short:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I found some [documentation online](https://learn.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/understanding-the-build-process) which reference things that seem useful to specify how I'd like to structure where my .dll files are dropped after they've been built, but my .csproj file looks very short and I have no idea where/how it is defined that all the test assemblies are put together with xunit.runner.visualstudio.dotnetcore.testadapter.dll.

Could someone help me understand where I have to fix these things ?

Thank you very much.

**Comment by bradwilson** [comment]
Dup of [xunit/xunit#2725](https://github.com/xunit/xunit/discussions/2725).
