### ISSUE TITLE
Tests with unusual names (?) not fully recognized

### ISSUE THREAD

**Issue by kurtschelfthout** [xunit/visualstudio.xunit#38]
![capture](https://cloud.githubusercontent.com/assets/164917/5592984/3041db96-91e5-11e4-8f4c-4d82c71c1d72.PNG)

(Bit of conjecture here, but pretty sure this is the cause) When a test has an "unusual" name, e.g. in the screenshot probably '(' or '%' or a number surrounded by spaces, the visual studio test runner does not seem to recognize it correctly. E.g. in the screenshot, the methods that are marked as "External" are actually in FsCheck.Test. Also, double clickig on the methods does not take me to the correct place in the source.

Such method names are pretty natural to create in F# using the backtick syntax.

They run fine, so this is mostly cosmetic.

**Comment by bradwilson** [comment]
We don't really control the sorting mechanism used by Visual Studio. We simply report the type and method information (and source info, if it's available) and at that point, it's out of our hands. I'd suggest opening this as an issue with the Visual Studio team and see if they can track down what causes it.

**Comment by kurtschelfthout** [comment]
Fair enough, thanks.

**Comment by bradwilson** [comment]
If they come up with something that needs to be fixed/changed on our side, please don't hesitate to let us know. Thanks!
