### ISSUE TITLE
How to run a single theory case with `dotnet test` filters

### ISSUE THREAD

**Issue by farlee2121** [xunit/visualstudio.xunit#387]
Is it possible to run a single theory case via the dotnet cli?

I've tried a variety of filter expressions.

Matching the exact name found in trx or by `--list-tests` doesn't seem to work 
example:  `(FullyQualifiedName=XUnitTests.theoryTest\(x: 2, y: 2, sum: 4\))` -> matches no tests

In fact, it appears to stop finding tests once the first parenthesis is added
`(FullyQualifiedName~XUnitTests.theoryTest\()` -> no matched tests

I also notice that filtering for the test method name exactly finds all of the theory cases
`(FullyQualifiedName=XUnitTests.theoryTest)`

I'm trying to better support xUnit theories in the [Ionide test explorer](https://github.com/ionide/ionide-vscode-fsharp/issues/1935)

**Comment by bradwilson** [comment]
You should be able to use `DisplayName` rather than `FullyQualifiedName`.

**Comment by farlee2121** [comment]
That works! Thank you!
