### ISSUE TITLE
NuGet runner doesn't find tests after uninstalling vsix

### ISSUE THREAD

**Issue by stephenroughley** [xunit/visualstudio.xunit#39]
We have a couple of workstations that had previously been using the VSIX to run XUnit tests in Visual Studio 2012 and 2013. Following removing the extension and installing the NuGet package as per the instruction here: http://xunit.github.io/docs/running-tests-in-vs.html we find the VS test explorer does not find any tests in the solution. 

I have CodeRush installed on my machine and I can run the tests via that but not via the VS Test UI.

Following some reading through other issues here I see one user had some success using devenv /ResetSettings but this has no effect in our case.

VS Info:
------------------------------------------------------------------------------------
Microsoft Visual Studio Professional 2012
Version 11.0.61030.00 Update 4
Microsoft .NET Framework
Version 4.5.50938

Installed Version: Professional

LightSwitch for Visual Studio 2012   04938-004-0033001-02278
Microsoft LightSwitch for Visual Studio 2012

Microsoft Visual Studio Tools for Applications 2012   04938-004-0033001-02278
Microsoft Visual Studio Tools for Applications 2012

Office Developer Tools   04938-004-0033001-02278
Microsoft Office Developer Tools

Team Explorer for Visual Studio 2012   04938-004-0033001-02278
Microsoft Team Explorer for Visual Studio 2012

Visual Basic 2012   04938-004-0033001-02278
Microsoft Visual Basic 2012

Visual C# 2012   04938-004-0033001-02278
Microsoft Visual C# 2012

Visual C++ 2012   04938-004-0033001-02278
Microsoft Visual C++ 2012

Visual F# 2012   04938-004-0033001-02278
Microsoft Visual F# 2012

Visual Studio 2012 Code Analysis Spell Checker   04938-004-0033001-02278
Microsoft® Visual Studio® 2012 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Visual Studio 2012 SharePoint Developer Tools   04938-004-0033001-02278
Microsoft Visual Studio 2012 SharePoint Developer Tools

.NET Memory Profiler   4.6
.NET Memory Profiler Visual Studio Integration Package

ASP.NET and Web Tools   2013.1.41108
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

ASP.NET Web Frameworks and Tools 2013.1   5.0.11113.0
For additional information, visit http://www.asp.net/

AWS Toolkit for Visual Studio 2012   1.6.2.0
AWS Toolkit for Visual Studio 2012.
Copyright 2011-2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.

This software includes third party software subject to the following copyrights:
- WPF Toolkit for charting and grid controls, Microsoft Public License (Ms-PL) 
  [http://wpf.codeplex.com/license]
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSONLint for JSON validation
  [https://github.com/zaach/jsonlint/blob/master/README.md]
- Noesis.Javascript.dll for JSON validation
  [http://javascriptdotnet.codeplex.com/license]

CodeRush for Visual Studio   14.1.6.0
CodeRush for Visual Studio

Devart Template Editor   1.0.9.0
Editor for T4 and Devart template files with syntax coloring and IntelliSense.

Mercurial Source Control Package   1.9
This package implements the functionalities of a source control provider package.

Multiline Search and Replace   1.6
Adds multiline search and replace functionality to Visual Studio.

NuGet Package Manager   2.8.50926.602
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.0
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

RenameVSWindowTitle 3   1.0
Information about my package

SQL Server Analysis Services   
Microsoft SQL Server Analysis Services Designer 
Version 11.0.3369.0

SQL Server Data Tools   11.1.40706.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 11.0.3369.0

SQL Server Reporting Services   
Microsoft SQL Server Reporting Services Designers 
Version 11.0.3369.0

VisualHG   1.1.5
Mercurial source contol provider.

Windows Installer XML Toolset   3.9.1006.0
Windows Installer XML Toolset version 3.9.1006.0
Copyright (c) Outercurve Foundation. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
------------------------------------------------------------------------------------

**Comment by hbelitzisap** [comment]
Are you sure you used **exactly** the package mentioned on http://xunit.github.io/docs/running-tests-in-vs.html ? I also had the same problem, but I accidently the first xunit runner package I found, not *xunit.runner.visualstudio*.

**Comment by stephenroughley** [comment]
Yup, schoolboy error. I had searched for that exact package 'xunit.runner.visualstudio' but it didn't show up so I chose the 'other' xUnit runners package. Only just noticed that I need to choose the pre-release runners package, by enabling 'Include Prerelease' in the NuGet package search.

Thank you for your help!
