### ISSUE TITLE
xUnit test runner doesn't respect parallel option under cog for test playlist

### ISSUE THREAD

**Issue by framlingham** [xunit/visualstudio.xunit#395]
We have been using this option in VS2022 17.7.6. I think it isn't working for us in our .NET Framework (.NET 4.8) solution for a test playlist.
![image](https://github.com/xunit/visualstudio.xunit/assets/12707910/05b62565-06ee-4c4d-827b-fe218b1506b5)
But after staring at the little spinners, we tried updating our `xunit.runner.json`:
```
{
	"longRunningTestSeconds": 600,
	"methodDisplay": "method",
	"methodDisplayOptions": "all",
	"parallelizeAssembly": false,
	"parallelizeTestCollections": false
}
```
Those last two seem to do it just fine, but I would have expected the VS option to control this too. I tried updating all our xUnit NuGets, but no luck:
* xunit 2.6.2 (at the same version are xunit.assert, xunit.core, xunit.extensibility.core, xunit.runner.console)
* xunit.runner.visualstudio 2.5.4
* xunit.abstractions 2.0.3
* xunit.analyzers 1.6.0

**Comment by framlingham** [comment]
I checked out similar issues, I can't find anything that seems to match or they are a lot older:
* https://github.com/xunit/visualstudio.xunit/issues/185
* https://github.com/xunit/visualstudio.xunit/issues/59
* https://github.com/xunit/visualstudio.xunit/issues/191
* https://github.com/xunit/visualstudio.xunit/issues/156

**Comment by bradwilson** [comment]
Can you provide a repro? Is this a single project or multiple projects? What is the behavior you're expecting vs. getting? Which `xunit.runner.json` options are you changing, and what result does that have?

If you've read through #191 you'd see that we have no control over how multi-assembly parallelism is executed in VSTest. We can instruct people on how to invoke `dotnet test` vs. `dotnet vstest` to try to simulate some parallelism options, but it's not clear to me what that menu option is intended to do.

**Comment by framlingham** [comment]
Sorry, I didn't get to your detailed response. So attempting to read it properly:

| Behavior | `dotnet test` | `dotnet vstest` | VS2022 UI |
| --- | --- | --- | --- |
| Run all tests in parallel | yes, forced default by processes | yes, --parallel and list all assemblies | yes, default |
| Run all tests in series | separate commands (per project) |yes, list all assemblies | done with mouse, one at a time |
| Run subset | nope | yes | yes |

But I get the impression that not much of this is controllable by xUnit or visualstudio.xunit. Who owns what so I can pester the right people/orgs?

**Comment by framlingham** [comment]
Sorry, I didn't get to your detailed response. So attempting to read it properly:

| Behavior | `dotnet test` | `dotnet vstest` | VS2022 UI |
| --- | --- | --- | --- |
| Run all tests in parallel | yes, forced default by processes | yes, --parallel and list all assemblies | yes, default |
| Run all tests in series | separate commands (per project) |yes, list all assemblies | done with mouse, one at a time |
| Run subset | nope | yes | yes |

But I get the impression that not much of this is controllable by xUnit.

**Comment by framlingham** [comment]
OK, so I tested these combinations. The first column mentiones whether the two json lines were included that specify sequential for assembly and test collections. I only ran the one test project/assembly:

| xunit.runner.json | UI parallel selected | Result |
| --- | --- | --- |
| with 2 lines | parallel | Ran sequentially, finished in 5min |
| with 2 lines | sequential | Ran sequentially, finished in 5min |
| without 2 lines | parallel | Ran parallel, stalled around 5min, stopped a bit later manually |
| without 2 lines | sequential | Ran sequentially, stalled around 5min, it aborted at about 9 minutes |

It looks like it would be nice if whoever wrote the UI part had some logic that hides the setting (or a hint that an xunit.runner.json is defined) or adds an option to do what the `xunit.runner.json` says.

**Comment by bradwilson** [comment]
I don't think there's anything we can do about this.

It's a well known "feature" of VSTest that the way they invoke us completely ignores the `parallelizeAssembly` setting that we have, so they're completely in control here and we have no say at all.

As for `parallelizeTestCollections`, that's definitely always in our control and should be independent of whatever you choose with the cog.

> Who owns what so I can pester the right people/orgs?

VSTest: https://github.com/microsoft/vstest/

You can bug all you want, but I can pretty much guarantee you they're going to tell you it's working as they want it to work. (Not to say that you shouldn't try, just trying not to get your hopes up.)

**Comment by alexTr3** [comment]
worst implemented library ever

1. no way to share context/fixture between test assemblies (important for test containers) NO .... ASSEMBLY FIXTURE IS not a solution..
2. no NORMAL easy understandable clear way to run test project one/assembly at a time 

how to make 100000 coders loose their time and mind..
