### ISSUE TITLE
Document how to enable long test names with the new nuget runner

### ISSUE THREAD

**Issue by fsateler** [xunit/visualstudio.xunit#40]
The only reference I have found to confguring is http://xunit.github.io/docs/running-tests-in-parallel.html, which of course makes no mention of how to enable long test names.

A related issue I found is xunit/xunit#222, but I tried adding `<add key="xunit.methodDisplay" value="classAndMethod"/>` to my test assembly's App.config but it did not work.

Please document how to configure the visual studio runner.

**Comment by bradwilson** [comment]
The configuration system is post Beta-5. If you pull a daily build from our CI builds on MyGet (https://myget.org/F/xunit), this should work. If you're waiting for an official build, it'll be another week or two.

**Comment by fsateler** [comment]
OK, thanks for the info. But please remember to document this when it is released :)

**Comment by fsateler** [comment]
With rc1 released today and the web site updated, I'm closing this issue.

Thanks!
