### ISSUE TITLE
Unable to run test from Visual Studio

### ISSUE THREAD

**Issue by rosieks** [xunit/visualstudio.xunit#41]
I have problem with running xUnit in Visual Studio from Test Explorer.

Tests output:

    ------ Discover test started ------
    An exception occurred while test discoverer 'KUnitTestDiscoverer' was loading tests. Exception: Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia 127.0.0.1:21686
    ========== Discover test finished: 0 found (0:00:20,7886244) ==========

project.json

    {
	"version": "1.0.0-*",
	"dependencies": {
		"xunit": "2.0.0-rc1-*",
		"xunit.runner.aspnet": "2.0.0-rc1-*",
		"xunit.runner.visualstudio": "2.0.0-rc1-*"
	},
	"commands": {
		"test": "xunit.runner.aspnet"
	},

	"frameworks": {
		"aspnet50": {
			"dependencies": {
			}
		},
		"aspnetcore50": {
			"dependencies": {
				"System.Runtime": "4.0.20-beta-22416"
			}
		}
	}
    }

**Comment by bradwilson** [comment]
I've been having issues with the ASP.NET runner in Visual Studio as well. The command line runner (`k run`) does work, though. I've been trying to investigate what the issues are with @vijayrkn.

**Comment by bradwilson** [comment]
There is an open bug in Connect related to this now: https://connect.microsoft.com/VisualStudio/feedback/details/1099770/test-explorer-does-not-discover-tests-in-project

**Comment by bradwilson** [comment]
The support for ASP.NET tests in v5 has been pulled for now, because the proper support has not be published to Nuget.org yet. When it is published, then the ASP.NET runner will be able to take advantage of it once again.
