### ISSUE TITLE
Why does "namespace + class name + method name" show in Test explorer when using rc2?

### ISSUE THREAD

**Issue by michaelsync** [xunit/visualstudio.xunit#44]
When using old version (xunit-2.0.0-beta5-build2785 and xunit.runner.visualstudio-0.99.9-build1021), it display only "method name" in Test explorer as shown in picture below.

![old](https://cloud.githubusercontent.com/assets/192911/6249195/9cda4986-b7c0-11e4-8096-60371ff5577c.png)

    <packages>
      <package id="xunit" version="2.0.0-beta5-build2785" targetFramework="net451" />
      <package id="xunit.abstractions" version="2.0.0-beta5-build2785" targetFramework="net451" />
      <package id="xunit.assert" version="2.0.0-beta5-build2785" targetFramework="net451" />
      <package id="xunit.core" version="2.0.0-beta5-build2785" targetFramework="net451" />
      <package id="xunit.runner.visualstudio" version="0.99.9-build1021" targetFramework="net451" />
    </packages>

When upgrade to new version (xunit-2.0.0-rc2-build2857 and xunit.runner.visualstudio-2.0.0-rc2-build1043), it shows "namespace + class name + method name" in Test explorer. Please refer to the screenshoot below. It looks weird and confusing. Is it the expected behavior? 

![new](https://cloud.githubusercontent.com/assets/192911/6249413/04c3951a-b7c2-11e4-8a3b-042b6c68eda0.png)

    <packages>
      <package id="xunit" version="2.0.0-rc2-build2857" targetFramework="net451" />
      <package id="xunit.abstractions" version="2.0.0-rc2-build2857" targetFramework="net451" />
      <package id="xunit.assert" version="2.0.0-rc2-build2857" targetFramework="net451" />
      <package id="xunit.core" version="2.0.0-rc2-build2857" targetFramework="net451" />
      <package id="xunit.extensibility.core" version="2.0.0-rc2-build2857" targetFramework="net451" />
      <package id="xunit.runner.visualstudio" version="2.0.0-rc2-build1043" targetFramework="net451" />
    </packages>

**Comment by MichaelFStarke** [comment]
In the V2RC, there is a configuration setting for that:
http://xunit.github.io/docs/configuration-files.html
see: xunit.methodDisplay

**Comment by michaelsync** [comment]
Thanks! Appreciated it!

**Comment by kevinpdpath** [comment]
The link above is broken. Here is a new one: http://xunit.github.io/docs/configuring-with-xml.html

**Comment by bradwilson** [comment]
Sorry, I forgot to add a redirect. Bad Brad. :-p
