### ISSUE TITLE
Test Explorer doesn't list tests with paket folder

### ISSUE THREAD

**Issue by ctaggart** [xunit/visualstudio.xunit#46]
Tests are not showing up in the Visual Studio 2013 Test Explorer using `paket 0.29.0`. If I copy `packages\xunit.runner.visualstudio` to `xunit.runner.visualstudio.2.0.0-rc2-build1043` then the tests show up. Is the test discovery expecting the NuGet version suffix somewhere?

![image](https://cloud.githubusercontent.com/assets/80104/6258162/268362a8-b77b-11e4-8d4a-2e5d340c2389.png)

/cc @forki

**Comment by bradwilson** [comment]
I have no idea what Visual Studio's algorithm is. I presume that, if you have fixed the .props and .targets to point to the right place, Visual Studio should just pick it up (since the binaries will end up in your bin folder).

**Comment by ctaggart** [comment]
The binaries do end up the the bin folder, but the tests don't get discovered until we copy that directory.

**Comment by forki** [comment]
You closed this? So it's working?

**Comment by bradwilson** [comment]
This is an external issue. If you are having problems with Visual Studio not finding DLLs, then please open an issue against Visual Studio: https://connect.microsoft.com/VisualStudio/
