### ISSUE TITLE
Too thick to figure out how to get 'xunit.methodDisplay' with Visual Studio

### ISSUE THREAD

**Issue by camkego** [xunit/visualstudio.xunit#47]
Sorry, I got the runner going, and can see my tests, but am unable to figure out how
to get the 'xunit.methodDisplay' to work with the Visual Studio runner.
Tried setting up the app.config in the project with the tests, but it isn't changing the behavior.

I might be in the minority about this, but I like xunit.methodDisplay=method as the default,
my fully qualified names are not really usable with the VS runner.

Any clues on how I can get the 'method' behavior with the VS runner?
Much thanks,
Cameron

**Comment by bradwilson** [comment]
There's an example here:

https://github.com/xunit/visualstudio.xunit.integration/blob/e5eed26050d7a4ada229e6c7b3fea07f9ee1654c/v2_net45/App.config

Just change "classAndMethod" to "method". Also, pulling the integration project and running some of those things from there can give you a good feeling for whether you're having general issues, or issues specific to your own project(s).

**Comment by camkego** [comment]
Brad, I guess part of my problem was I was using the Stable Nuget, which gave me 1.9.2, which apparently does not support the App.config settings.
Unfortunately, going with the latest Prerelease (2.0.0-rc2-build2857) only works if I upgrade my project to .Net Framework 4.5

Is there a way to get the App.config support along with support for the 4.0 Net Framework?
Thanks

**Comment by bradwilson** [comment]
Unfortunately, no.

The majority of the configuration items are v2 only. You don't have to upgrade your production assemblies to 4.5, just the unit tests. If that's still not acceptable, then I'm afraid you're stuck until you can.

Sorry. :(
