### ISSUE TITLE
Error when running xunit tests through MSBuild

### ISSUE THREAD

**Issue by WadeBarnes** [xunit/visualstudio.xunit#49]
Using:
* VS 2013
* xunit 2.0.0-rc3-build2880 installed packages through NuGet

Following the example I created the following script:

```XML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <UsingTask AssemblyFile=".\packages\xunit.runners.2.0.0-rc3-build2880\tools\xunit.runner.msbuild.dll" TaskName="Xunit.Runner.MSBuild.xunit" />

  <ItemGroup>
    <TestAssemblies Include="**/ServerTests.dll" />
  </ItemGroup>

  <Target Name="Test">
    <xunit Assemblies="@(TestAssemblies)" Verbose="true" Xml="DARSTestResults.xml" />
  </Target>
</Project>
```

Which produces the following cmd line output and error(s).

<pre>
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/26/2015 11:57:31 AM.
Project "C:\DARS\build.xml" on node 1 (Test target(s)).
Test:
  xUnit.net MSBuild runner (32-bit .NET 4.0.30319.34209)
    Discovering: ServerTests
    Discovered:  ServerTests
    Starting:    ServerTests
      START: ServerTests.LognotesControllerTests.GetLognotes
      START: ServerTests.LognotesTests.GetNonExistingLognote
      PASS:  ServerTests.LognotesControllerTests.GetLognotes
      START: ServerTests.LognotesControllerTests.GetNonExistingLognote
      PASS:  ServerTests.LognotesControllerTests.GetNonExistingLognote
      START: ServerTests.LognotesControllerTests.GetExistingLognote
      PASS:  ServerTests.LognotesControllerTests.GetExistingLognote
      PASS:  ServerTests.LognotesTests.GetNonExistingLognote
      START: ServerTests.LognotesTests.GetExistingLognote
      PASS:  ServerTests.LognotesTests.GetExistingLognote
      START: ServerTests.LognotesTests.GetLognotes
      PASS:  ServerTests.LognotesTests.GetLognotes
    Finished:    ServerTests
    Discovering: ServerTests
C:\DARS\build.xml(24,5): error : System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
C:\DARS\build.xml(24,5): error : Parameter name: C:\DARS\ServerTests\obj\Debug\ServerTests.dll
C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.CreateInnerController()
C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.get_InnerController()
C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
C:\DARS\build.xml(24,5): error :    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
  === TEST EXECUTION SUMMARY ===
     ServerTests  Total: 6, Errors: 0, Failed: 0, Skipped: 0, Time: 1.723s
Done Building Project "C:\DARS\build.xml" (Test target(s)) -- FAILED.

Build FAILED.

"C:\DARS\build.xml" (Test target) (1) ->
(Test target) -> 
  C:\DARS\build.xml(24,5): error : System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
C:\DARS\build.xml(24,5): error : Parameter name: C:\DARS\ServerTests\obj\Debug\ServerTests.dll
  C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.CreateInnerController()
  C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.get_InnerController()
  C:\DARS\build.xml(24,5): error :    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
  C:\DARS\build.xml(24,5): error :    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)

    0 Warning(s)
    5 Error(s)

Time Elapsed 00:00:03.16
</pre>

The xunit report indicates all the tests passed:
```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="C:\DARS\ServerTests\bin\Debug\ServerTests.DLL" environment="32-bit .NET 4.0.30319.34209 [collection-per-class, parallel]" test-framework="xUnit.net 2.0.0.2880" run-date="2015-02-26" run-time="11:57:32" config-file="C:\DARS\ServerTests\bin\Debug\ServerTests.dll.config" total="6" passed="6" failed="0" skipped="0" time="1.723" errors="0">
    <errors />
    <collection total="3" passed="3" failed="0" skipped="0" name="Test collection for ServerTests.LognotesTests" time="1.578">
      <test name="ServerTests.LognotesTests.GetNonExistingLognote" type="ServerTests.LognotesTests" method="GetNonExistingLognote" time="1.5732528" result="Pass" />
      <test name="ServerTests.LognotesTests.GetExistingLognote" type="ServerTests.LognotesTests" method="GetExistingLognote" time="0.0009195" result="Pass" />
      <test name="ServerTests.LognotesTests.GetLognotes" type="ServerTests.LognotesTests" method="GetLognotes" time="0.0040809" result="Pass" />
    </collection>
    <collection total="3" passed="3" failed="0" skipped="0" name="Test collection for ServerTests.LognotesControllerTests" time="0.549">
      <test name="ServerTests.LognotesControllerTests.GetLognotes" type="ServerTests.LognotesControllerTests" method="GetLognotes" time="0.5459461" result="Pass" />
      <test name="ServerTests.LognotesControllerTests.GetNonExistingLognote" type="ServerTests.LognotesControllerTests" method="GetNonExistingLognote" time="0.0021583" result="Pass" />
      <test name="ServerTests.LognotesControllerTests.GetExistingLognote" type="ServerTests.LognotesControllerTests" method="GetExistingLognote" time="0.0010903" result="Pass" />
    </collection>
  </assembly>
  <assembly />
</assemblies>
```

**Comment by bradwilson** [comment]
Your glob is wrong. Here's your hint:

```
C:\DARS\build.xml(24,5): error : Parameter name: C:\DARS\ServerTests\obj\Debug\ServerTests.dll
```

Your glob matches the `obj` folder, which I'm sure you didn't mean (you only want the DLL from the `bin` folder).

**Comment by WadeBarnes** [comment]
Thanks.  Sure enough it works.  :-) To blind to see the forest for the trees.
