### ISSUE TITLE
Visual Studio fails to detect tests, if runner is installed to a folder without version

### ISSUE THREAD

**Issue by JanBessai** [xunit/visualstudio.xunit#50]
When installing the runner to the default location `packages\xunit.runner.visualstudio.2.0.0-rcN-buildABCD` everything works fine, but as soon as the installation folder changes, visual studio stops finding the runner.
This is especially relevant in manual dependency management settings, where NuGet is invoked with `-ExcludeVersion`.

You can find a minimal project triggering the bug in 

https://github.com/JanBessai/XunitVSRunnerTest 
and
https://github.com/JanBessai/XunitVSRunnerTest/tree/FailingVersion 

A quick search revealed no obvious reason for this bug. Even a crude `grep -R build1049 packages` did not find anything indicating a hard-coded folder location.

**Comment by bradwilson** [comment]
This is a dup of #46, and I'm going to close it because we have no control over this. The discovery is done by Visual Studio.

Please open an issue in the Visual Studio Connect site: https://connect.microsoft.com/VisualStudio/
