### ISSUE TITLE
Test Explorer shows fully qualified name of test instead of just function name

### ISSUE THREAD

**Issue by StephenCavender** [xunit/visualstudio.xunit#51]
Before I updated the plugin the explorer had the tests listed by the function name below the Fact and Traits. Now I have to expand the explorer to see the actual name of my tests taking up half of my screen.
I have 2.0.0-rc4-build1049 installed.

**Comment by bradwilson** [comment]
This is a per-project configuration now.

http://xunit.github.io/docs/configuration-files.html

See the setting for `xunit.methodDisplay`.

**Comment by StephenCavender** [comment]
Apologies, thanks for the link!

**Comment by bradwilson** [comment]
No need to apologize. :) Let us know if that doesn't work for you.

**Comment by StephenCavender** [comment]
Yeah I'm still having issues. I've added the App.config to the project that contains my test cases but it doesn't seem to be caring that its there :(

**Comment by bradwilson** [comment]
Note that you will have to re-build (to trigger a re-discovery in Visual Studio) after changing the setting.

**Comment by StephenCavender** [comment]
Right, I've tried cleaning and rebuilding but I still get the long test names. It's creating the Namespace.dll.config file with the correct settings but the project still doesn't seem to be reading it.
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="xunit.methodDisplay" value="method"/>
  </appSettings>
</configuration>

Stephen Cavender

Date: Mon, 30 Mar 2015 15:45:34 -0700

**Comment by bradwilson** [comment]
Just to be sure that you did the right thing, you should have:

1. Right clicked on the project inside Solution Explorer
2. Click `Add` > `New Item...`
3. Chose `Application Configuration File`
4. The system adds a file named `App.config`
5. You put your configuration changes into that file

Is this what you did? If not, do that. :)

**Comment by StephenCavender** [comment]
I did do that :( And after I did that, I cleaned and rebuilt the entire solution. And then I continued to bang my head against my desk because my test names are super long lol. Does the App.config file need special configuration? or my solution/project need something to tell it to point to the App.config?

**Comment by bradwilson** [comment]
If you clone the Visual Studio Integration project, does that work as expected? Just go into the v2_net45 project and update the `App.config` to use `method` instead of `classAndMethod`.

https://github.com/xunit/visualstudio.xunit.integration/

(Don't worry if you have some unsupported things like ASP.NET 5 or the Windows Phone stuff.)

**Comment by StephenCavender** [comment]
I think I found my problem, my project had a reference to an xunit.dll file that is at version 1.9.1.1600.
