### ISSUE TITLE
Should the VS runner skip also Xamarin.iOS target framework assemblies?

### ISSUE THREAD

**Issue by kzu** [xunit/visualstudio.xunit#53]
The [VsTestRunner](https://github.com/xunit/visualstudio.xunit/blob/1e28898d24cbc76e2ff5c560a145936a7aa4e240/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L106-L107) is already skipping MonoTouch and MonoDroid, should it also skip Xamarin.iOS, which our new target framework for the new Unified API (32-64bit) for iOS?

**Comment by bradwilson** [comment]
Probably so.

**Comment by bradwilson** [comment]
Fixed by #56.
