### ISSUE TITLE
Should the runner be discovering tests in vs 2015 ctp 6?

### ISSUE THREAD

**Issue by glennsills** [xunit/visualstudio.xunit#54]

**Comment by bradwilson** [comment]
**Yes** for: Desktop, PCL, Windows 8, Windows Phone 8, Windows Universal (Windows 8.1, Windows Phone 8.1, Windows 10).

**No** for: everything else.

(Note: ASP.NET 5 will be supported in 2.1 through the `xunit.runner.aspnet` package.)
