### ISSUE TITLE
Visual Studio test runner does not work with VS2015 and new ASP.NET vNext library projects

### ISSUE THREAD

**Issue by gingters** [xunit/visualstudio.xunit#55]
I have a simple Asp.Net vNext library and a corresponding xunit unit test project.

Based on the information here: http://stackoverflow.com/questions/27018778/how-can-i-run-xunit-unit-tests-with-vs2015-preview and from some other similar issues here on Github, I did not install the vsix but just referenced the xunit.runner.visualstudio NuGet package.
I also followed the 'Getting started with xUnit.net and ASP.NET 5' article from the documentation, but info on VS seems incorrect.

Problem: The Visual Studio test explorer in VS2015 CTP does not find any of the tests.

All tests run fine on console, when I issue `k test`, though.

My Project.json:

    {
    	"version": "1.0.0-*",
    	"compilationOptions": {
    		"warningsAsErrors": true
    	},
    	"dependencies": {
    		"xunit": "2.0.0-rc3-*",
    		"xunit.runner.aspnet": "2.0.0-rc3-*",
    		"xunit.runner.visualstudio": "2.0.0-*",
    		"MyProject.Services": "1.0.0-*"
    	},
    	"frameworks": {
    		"aspnet50": { },
    		"aspnetcore50": {
    			"dependencies": {
    				"System.Runtime": "4.0.20-beta-22523"
    			}
    		}
    	},
    	"commands": {
    		"test": "xunit.runner.aspnet",
    		"testvs": "xunit.runner.visualstudio"
    	}
    }

Besides this, I also tried with all available versions of the xunit.runner.visualstudio package on NuGet.org, all to no avail.

**Comment by bradwilson** [comment]
The intention is that this will be supported in 2.1 Beta 1 (and you don't need "xunit.runner.visualstudio" referenced, as the "xunit.runner.aspnet" will provide both a console run experience and a Visual Studio run experience).

We actually have bits ready to go for this, but Visual Studio is not correctly discovering them. I'm waiting for @davidfowl to let me know what the issue is.
