### ISSUE TITLE
xunit.methodDisplay setting not applying to test explorer name display (xunit 1.9.2)

### ISSUE THREAD

**Issue by laurencee** [xunit/visualstudio.xunit#57]
Hello,

I am running xunit 1.9.2 with the visual studio runner nuget package (2.0.0) and have set xunit.methodDisplay in my app.config for my test project:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="xunit.methodDisplay" value="method"/>
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="xunit.extensions" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.9.2.1705" newVersion="1.9.2.1705" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

I have deleted the %TEMP%\VisualStudioTestExplorerExtensions but that didn't make any difference.

All the tests still showing up as fully qualified names in test explorer. (VS2013 update 4)

**Comment by bradwilson** [comment]
That is expected behavior, as this is documented as a v2-only feature. http://xunit.github.io/docs/configuration-files.html

![2 0](https://cloud.githubusercontent.com/assets/16944/6775567/2a4ccb02-d0f0-11e4-972b-6ea7b05c33dd.png)
