### ISSUE TITLE
Visual Studio runner ignores parallelization settings.

### ISSUE THREAD

**Issue by Zoltu** [xunit/visualstudio.xunit#59]
1. Visual Studio 2013 Update 4
1. New Class Library
1. Add xunit 2.0.0 NuGet package
1. Add xunit.runner.visualstudio 2.0.0 NuGet package
1. Add fact to class.
1. Create another class with a fact.
1. Put a 5 second sleep and assertion in both facts.
1. Build.
1. Open Visual Studio Test Explorer.
1. Run All
--> Notice that the tests took over 10 seconds to run.

I have also tried adding `[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly, MaxParallelThreads = 10)]` to my AssemblyInfo.cs file but the problem persisted.

There used to be an option in Visual Studio Tools > Options > xUnit, but this appears to have gone away with the death of the Visual Studio extension.

**Comment by Zoltu** [comment]
I have also tried adding `[Collection("Our Test Collection #1")]` to both test classes.  Same problem.

**Comment by Zoltu** [comment]
Hmm... I must have done one of the steps wrong.  I went back through and it worked.  I did need to use `CollectionBehavior(CollectionBehavior.CollectionPerClass)]` though.

**Comment by bradwilson** [comment]
`CollectionPerClass` is the default behavior. You shouldn't need any attribute at all to get that behavior (though setting `CollectionPerAssembly` would've caused the problems you were seeing, since it effectively disables all parallelization by default).
