### ISSUE TITLE
Runner occasionally showing error messages about trying to access unloaded app domains

### ISSUE THREAD

**Issue by bradwilson** [xunit/visualstudio.xunit#6]
(Moved from https://github.com/xunit/xunit/issues/33)

**Comment by giggio** [comment]
Just FYI: I just got that error once on VS 2015 CTP 5, with runner `2.0.0-rc1-build1030`. It ran the tests, but showed the message on the Output window. It is not happening anymore.

**Comment by khayes** [comment]
I'm also experiencing this when running tests with xunit.console.clr4.x86.exe. In my particular case I'm invoking the console runner via powershell.

The dll I am testing is as simple as it can get, it only contains one test which is the following:

[Fact]
[Trait("Category", "UnitTest")]
public void TestMethod()
{
Assert.True(true);
}

**Comment by DerAlbertCom** [comment]
Happens also in Visual Studio Online (current non pre bits)

**Comment by bradwilson** [comment]
This issue was moved to xunit/xunit#490
