### ISSUE TITLE
'No source available' when generic base class defines tests

### ISSUE THREAD

**Issue by adamchester** [xunit/visualstudio.xunit#61]
Tests that use a base class with a generic type parameter are not being discovered correctly. The Test Explorer reports `no source available` as the below screenshot shows:

![image](https://cloud.githubusercontent.com/assets/570470/7104015/072799c8-e107-11e4-8144-4879d2e2f7c4.png)

**Comment by bradwilson** [comment]
This information is provided by Visual Studio (not xUnit.net). It's possible that the source information provider does not correctly deal with generic methods.

**Comment by adamchester** [comment]
Sounds like this is not really a bug in xUnit.net then. Closing.
