### ISSUE TITLE
Execution Time out

### ISSUE THREAD

**Issue by GibbOne** [xunit/visualstudio.xunit#64]
IMHO an execution time out per test should be very usefull. All the more "TimeOut" parameter is no longer supported in v2 "FactAttribute". (https://gist.github.com/bradwilson/9457177#timeout-property-has-been-removed-from-factattribute).

**Comment by bradwilson** [comment]
This is the wrong place to ask this question, as this forum is limited to issues related to the Visual Studio runner for xUnit.net. The correct place is: https://github.com/xunit/xunit/issues

That said, we are not planning to add this feature. It can be added via extensibility, with the caveat that parallelization must be turned off in order for it to be effective.
