### ISSUE TITLE
xunit.runners.1.9.2 - Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables

### ISSUE THREAD

**Issue by mayurj111** [xunit/visualstudio.xunit#68]
When I am running my xunit tests, which uses MS Fakes under visual studio 2013 it pass the tests. But when I try to run it using xunit.runners.1.9.2 from commandline it gives below error,

Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException:
Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables.

Any idea?

**Comment by bradwilson** [comment]
You can't use our runners to run tests with Fakes. You have to use the Visual Studio runner (either the GUI or command line). This is a limitation of the Fakes library.

**Comment by mayurj111** [comment]
Thanks. Using VSTest.console.exe has solved the issue and not giving any errors.
