### ISSUE TITLE
running Xunit tests along with vstest.console.exe runner not generating trx file, TestResults empty

### ISSUE THREAD

**Issue by mayurj111** [xunit/visualstudio.xunit#69]
I am using Xunit test framework along with Visual Studio 2013. Tests run fine in Visual Studio environment.

However, when I try using command line using VSTest.console.exe it does not give any TRX output and returns empty Test Results folder on build server.

Not sure, if Xunit is causing this issue or VStest. 

c:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" 
"C:\UnitTest\MyTests.dll"
 /settings:"C:\UnitTest\output.runsettings" 
 /UseVsixExtensions:"true" 
 /InIsolation 
 /Logger:"trx"

<?xml version="1.0" encoding="UTF-8"?>
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
  </RunConfiguration>
</RunSettings>

**Comment by bradwilson** [comment]
xUnit.net has nothing to do with TRX. Assuming that third party results are supposed to be converted into TRX, then it's `vstest.console.exe` that's failing to do the conversion.

**Comment by mayurj111** [comment]
ok. Thanks for clarification.
