### ISSUE TITLE
xunit doesn't recognize project references

### ISSUE THREAD

**Issue by vensaadmin** [xunit/visualstudio.xunit#73]
When running with xunit in Visual Studio 2015, if I use a project reference instead of a assembly reference xunit fails during discovery. 

To be clearer, a reference assembly is used to resolve linkages.  Visual Studio allows you to use the project rather than specifying the actual assembly.  This permit switchable assemblies based on the target type.  

By trial and error, I was able to narrow the problem and work around the problem by using the actual assembly reference rather than use the project reference.  I would be great if I can get xunit to work with the project reference.

**Comment by bradwilson** [comment]
Sorry, we have no control over this. This is a function of how the Visual Studio Test Explorer extensibility works with NuGet packages.
