### ISSUE TITLE
Method 'Find' in type 'Xunit.XunitFrontController' ... does not have an implementation.

### ISSUE THREAD

**Issue by robblovell** [xunit/visualstudio.xunit#74]
I am getting the error with win81 and visualstudio 2013 Version 12.0.31101.00 Update 4:

An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Method 'Find' in type 'Xunit.XunitFrontController' from assembly 'xunit.runner.utility, Version=2.0.0.2738, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' does not have an implementation.

or more succinctly: 

'VsTestRunner' Method 'Find' in type 'Xunit.XunitFrontController' from assembly 'xunit.runner.utility does not have an implementation.

When Visual Studio is trying to discover xunit tests.  I have made sure the Visual Studio Xunit runner extension is uninstalled, deleted the cache for nuget (both the AppData one and the packages directory), removed all items from temporary directories, reinstalled from scratch xunit 2.1.0-beta3-build3029 (Prerelease) and xunit.net runner for visual studio 2.1.0-beta3-build1069 (Prerelease), both of which are the latest available nuget packages that I can see.  I have worked through several google searches trying various fixes, none of which work. 

Visual studio information:
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.6.00057

Installed Version: Ultimate

Architecture and Modeling Tools   06181-004-0451047-02001
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2013   06181-004-0451047-02001
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06181-004-0451047-02001
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06181-004-0451047-02001
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451047-02001
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451047-02001
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451047-02001
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06181-004-0451047-02001
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06181-004-0451047-02001
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools   12.4.60320.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

AWS Toolkit for Visual Studio 2013   1.6.4.1
AWS Toolkit for Visual Studio 2013.
Copyright 2011-2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.

This software includes third party software subject to the following copyrights:
- WPF Toolkit for charting and grid controls, Microsoft Public License (Ms-PL) 
  [http://wpf.codeplex.com/license]
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSONLint for JSON validation
  [https://github.com/zaach/jsonlint/blob/master/README.md]
- Noesis.Javascript.dll for JSON validation
  [http://javascriptdotnet.codeplex.com/license]

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Git Source Control Provider   1.0.0.0

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure HDInsight HQL Service   2.0.0.0000
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.0.0000
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.5
Microsoft Azure Tools for Microsoft Visual Studio 2013 - v2.5.21104.1601

MySQL for Visual Studio   1.2.3
Data design and management tools for MySQL.  Copyright © 2007-2014 Oracle, Inc.

NuGet Package Manager   2.8.60318.734
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.40429
Microsoft Office Developer Tools for Visual Studio 2013 ENU

PowerShell Tools   1.3
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

VSCommands for Visual Studio 2013   12.0
VSCommands for Visual Studio 2013

Web Essentials 2013   2.5.3
Adds many useful features to Visual Studio for web developers.

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin.Android   4.12.02001 (a1e3982a)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   1.10.47 (3d6a125d)
Visual Studio extension to enable development for Xamarin.iOS

**Comment by robblovell** [comment]
Similar issue, but different: https://github.com/xunit/visualstudio.xunit/issues/37

**Comment by robblovell** [comment]
Worked through this with no luck, but it might be a clue: http://stackoverflow.com/questions/29632900/xunit-cannot-discover-tests-after-upgrading-to-v2

I have a file
...\AppData\Local\Temp\VisualStudioTestExplorerExtensions\xunit.runner.visualstudio.0.99.8
 that is brought in, not sure if it's supposed to be there.

**Comment by bradwilson** [comment]
Two thoughts:

1. We've fixed several bugs here. Can you try the 2.0.1 RC? http://xunit.github.io/release-notes/2015-07-04.html

2. The documentation page talks about the hazards of corruption of the cache that Visual Studio keeps for runners. I opened a bug with Microsoft but it was closed as "no repro". We give people explicit instructions that, when they're having trouble with the VS runner, they very first thing they should do is shut down all instances of VS and clear out that cache. http://xunit.github.io/docs/running-tests-in-vs.html
